---
title: "ICM testing"
output:
  pdf_document: default
  html_document: default
  word_document: 
    #reference_docx: template.docx
editor_options:
  chunk_output_type: console
---

The data is now available to test this on at least 81 stocks.  All of the NE Atlantic stocks (ICES) have been through the QA/QC process and we are happy with those data (Sept 1, 2022).  Let's see if we can get this to work on all the stocks with sufficient data... 

```{r, load-stuff,echo=F, message=F, warning=F, fig.width=6, fig.height=4}
# OK, so using the ICES assessments here's what we get for North Sea cod.
library(readxl)
library(tidyverse)
library(rio)
library(ggthemes)
library(cowplot)

loc <- 'C:/Users/Owner/Documents/GitHub/ICM'
source(paste0(loc,"/Scripts/functions/backwards_sim.R"))
source(paste0(loc,"/Scripts/functions/tuning_sim_version_2.R"))
load(file = paste0(loc,"/Results/model_inputs.Rdata"))

Stocks <- Stocks[grep("WGNSSK",Stocks)]
# Haddock in NS is busted before 1972, not sure why, but I'm chucking all that data here in a very sloppy way
  ns.had <- "ICES-WGNSSK_NS  4-6a-20_Melanogrammus_aeglefinus"
  years.tmp[[ns.had]] <- years.tmp[[ns.had]][-1:-7]
  pnm.tmp[[ns.had]] <- pnm.tmp[[ns.had]][-1:-7,]
  waa.tmp[[ns.had]] <- waa.tmp[[ns.had]][-1:-7,]
  #ages.tmp[[ns.had]] <- ages.tmp[[ns.had]][-1:-7]
  rem.tmp[[ns.had]] <- rem.tmp[[ns.had]][-1:-7,]
  mx.tmp[[ns.had]] <- mx.tmp[[ns.had]][-1:-7,]
  #N.end[[ns.had]] <- NE.tmp[[ns.had]][-1:-7]
  vpa.tmp[[ns.had]] <- vpa.tmp[[ns.had]][-1:-7]
  am.tmp[[ns.had]] <- am.tmp[[ns.had]][-1:-7,]
  
  ns.had <- "ICES-WGNSSK_NS4 _Solea_solea"
  years.tmp[[ns.had]] <- years.tmp[[ns.had]][-1:-7]
  pnm.tmp[[ns.had]] <- pnm.tmp[[ns.had]][-1:-7,]
  waa.tmp[[ns.had]] <- waa.tmp[[ns.had]][-1:-7,]
  #ages.tmp[[ns.had]] <- ages.tmp[[ns.had]][-1:-7]
  rem.tmp[[ns.had]] <- rem.tmp[[ns.had]][-1:-7,]
  mx.tmp[[ns.had]] <- mx.tmp[[ns.had]][-1:-7,]
  #N.end[[ns.had]] <- NE.tmp[[ns.had]][-1:-7]
  vpa.tmp[[ns.had]] <- vpa.tmp[[ns.had]][-1:-7]
  am.tmp[[ns.had]] <- am.tmp[[ns.had]][-1:-7,]
  
  
```


```{r, run-mods,echo=F, message=F, warning=F}

back.res <- NULL
back.ts <- NULL
back.ts.quants <- NULL
for.res <- NULL
for.ts <- NULL
for.ts.quants <- NULL
tuned.res <- NULL
for(i in Stocks)
{
  years <- years.tmp[[i]]
  prop.nat.mort <- pnm.tmp[[i]] 
  weight.age <- waa.tmp[[i]] 
  ages <- ages.tmp[[i]] 
  rem <- rem.tmp[[i]] 
  mx <- mx.tmp[[i]] 
  N.end <- NE.tmp[[i]] 
  vpa.abund <- vpa.tmp[[i]] 
  age.mat <- am.tmp[[i]]
  

#
  # N.end <- vpa.abund[length(vpa.abund)]
   tunes <- tune.sim(years,
                     n.steps = 10,
                     tune.par=0.1,
                     abund.ts = vpa.abund,
                     mat.age = age.mat,
                     nm = -(log(1-prop.nat.mort)),
                     w.age = weight.age,
                     ages = ages,
                     rems = rem$rem,
                     fecund = mx,
                     N.end = N.end,
                     pop.model = 'exponential',
                     tuner = "nm")

   tuned.res[[i]] <- tunes
} # end i in Stocks look



# Save all these
 save.image(file = paste0(loc,"/Results/NS_tuned_sim_results.RData"))
 
```


```{r, make-figs,echo=F, message=F, warning=F, fig.width=6, fig.height=4}

# Now we can run the figures separately.
#tuned.res <- readRDS(file = "D:/Github/ICM/Results/tuned_fits.Rds")
#load(file = "D:/Github/ICM/Results/model_inputs.Rdata")
load(file = paste0(loc,"/Results/NS_tuned_sim_results.RData"))


for(i in Stocks)
{
  # Unpack the lists
  tunes <- tuned.res[[i]] 
  missing_rem <- mr.tmp[[i]] 

  # Comparing our new time series with the old
  p2 <- ggplot() +
          geom_line(data=tunes$res, aes(x=years,y=abund),color='blue') +
          geom_line(data=tunes$res, aes(x=years,y=vpa.abund),color='black') +
          xlab("") +
          ylab("Abundance (1000s)") +
          #geom_line(data=did.it.work %>% dplyr::filter(sim == "VPA"),aes(x=years,y=abund),color='black',size=2) +
          #scale_y_continuous(breaks = seq(0,3e6,by=5e5)) + scale_x_continuous(breaks = seq(1960,2025,by=5)) +
          theme_few() + theme(legend.position = 'none') +
          ggtitle(i) #+
          #geom_text(data=did.it.work[did.it.work$missing=="missing",], aes(x=years, y=abund, label="?"))
  save_plot(plot = p2, filename = paste0(loc,"/Figures/NS_sims/tunes/", i, "/tunded_vs_vpa_", i, ".png"), 
            base_width = 6,base_height = 4)
  
  # # Comparing the absolute miss from the tuned time series
  #  p3 <- ggplot() +
  #         #geom_line(data=tunes$res, aes(x=year,y=lotka.n),color='blue') +
  #         geom_line(data=tunes$res[-1,], aes(x=year,y=diff.n),color='red') +
  #         xlab("") +
  #         ylab("Difference in abundance (1000s)") +
  #         #geom_line(data=did.it.work %>% dplyr::filter(sim == "VPA"),aes(x=years,y=abund),color='black',size=2) +
  #         #scale_y_continuous(breaks = seq(0,3e6,by=5e5)) + scale_x_continuous(breaks = seq(1960,2025,by=5)) +
  #         theme_few() + theme(legend.position = 'none') + 
  #         ggtitle(i) 
  #         #geom_text(data=did.it.work[did.it.work$missing=="missing",], aes(x=years, y=abund, label="?"))
  # save_plot(plot = p3, filename = paste0(loc,"/Figures/NS_sims/tunes/", i, "/diff_N_", i, ".png"), 
  #           base_width = 6,base_height = 4)
  # 
  # # What percentage (mean) difference
  #  p4 <- ggplot() +
  #         #geom_line(data=tunes$res, aes(x=year,y=lotka.n),color='blue') +
  #         geom_line(data=tunes$res[-1,], aes(x=year,y=per.diff.n),color='red') +
  #         xlab("") +
  #         ylab("Difference in abundance (%)") +
  #         #geom_line(data=did.it.work %>% dplyr::filter(sim == "VPA"),aes(x=years,y=abund),color='black',size=2) +
  #         #scale_y_continuous(breaks = seq(0,3e6,by=5e5)) + scale_x_continuous(breaks = seq(1960,2025,by=5)) +
  #         theme_few() + theme(legend.position = 'none') + 
  #         ggtitle(i) #+ ylim(c(-100,100))
  #         #geom_text(data=did.it.work[did.it.work$missing=="missing",], aes(x=years, y=abund, label="?"))
  # save_plot(plot = p4, filename = paste0(loc,"/Figures/NS_sims/tunes/", i, "/per_diff_N_", i, ".png"), 
  #           base_width = 6,base_height = 4)
  # 
  # 
  #     p8 <- ggplot() +
  #         geom_line(data=tunes$res[-1,], aes(x=year,y=r),color='blue') +
  #         xlab("") +
  #         ylab("Lotka r") +
  #         #geom_line(data=did.it.work %>% dplyr::filter(sim == "VPA"),aes(x=years,y=abund),color='black',size=2) +
  #         #scale_y_continuous(breaks = seq(0,3e6,by=5e5)) + scale_x_continuous(breaks = seq(1960,2025,by=5)) +
  #         theme_few() + theme(legend.position = 'none') +
  #         ggtitle(i) #+
  #         #geom_text(data=did.it.work[did.it.work$missing=="missing",], aes(x=years, y=abund, label="?"))
  # save_plot(plot = p8, filename = paste0(loc,"/Figures/NS_sims/tunes/", i, "/Lotka_r_", i, ".png"), 
  #           base_width = 6,base_height = 4)
  #    
  #    # Difference in m's
  #  p5 <- ggplot() +
  #         geom_line(data=tunes$res[-1,], aes(x=year,y=diff.m),color='red') +
  #         xlab("") +
  #         ylab("Difference in natural mortality (Instantaneous)") +
  #         #geom_line(data=did.it.work %>% dplyr::filter(sim == "VPA"),aes(x=years,y=abund),color='black',size=2) +
  #         #scale_y_continuous(breaks = seq(0,3e6,by=5e5)) + scale_x_continuous(breaks = seq(1960,2025,by=5)) +
  #         theme_few() + theme(legend.position = 'none') + 
  #         ggtitle(i) #+ ylim(c(-100,100))
  #         #geom_text(data=did.it.work[did.it.work$missing=="missing",], aes(x=years, y=abund, label="?"))
  # save_plot(plot = p5, filename = paste0("D:/Github/ICM/Figures/tuned/", i, "/diff_m_", i, ".png"), base_width = 6,base_height = 4)
  #    # % Difference in m's
  #  p6 <- ggplot() +
  #         geom_line(data=tunes$res[-1,], aes(x=year,y=per.diff.m),color='red') +
  #         xlab("") +
  #         ylab("Difference in natural mortality (%)") +
  #         #geom_line(data=did.it.work %>% dplyr::filter(sim == "VPA"),aes(x=years,y=abund),color='black',size=2) +
  #         #scale_y_continuous(breaks = seq(0,3e6,by=5e5)) + scale_x_continuous(breaks = seq(1960,2025,by=5)) +
  #         theme_few() + theme(legend.position = 'none') + 
  #         ggtitle(i) #+ ylim(c(-100,100))
  #         #geom_text(data=did.it.work[did.it.work$missing=="missing",], aes(x=years, y=abund, label="?"))
  # save_plot(plot = p6, filename = paste0("D:/Github/ICM/Figures/tuned/", i, "/per_diff_m_", i, ".png"), base_width = 6,base_height = 4)
  # 
  #  p7 <- ggplot() +
  #         geom_line(data=tunes$res[-1,], aes(x=year,y=mn.m),color='blue') +
  #         geom_line(data=tunes$res[-1,], aes(x=year,y=vpa.m),color='black') +
  #         xlab("") +
  #         ylab("Natural mortality (Instantaneous)") +
  #         #geom_line(data=did.it.work %>% dplyr::filter(sim == "VPA"),aes(x=years,y=abund),color='black',size=2) +
  #         #scale_y_continuous(breaks = seq(0,3e6,by=5e5)) + scale_x_continuous(breaks = seq(1960,2025,by=5)) +
  #         theme_few() + theme(legend.position = 'none') +
  #         ggtitle(i) #+
  #         #geom_text(data=did.it.work[did.it.work$missing=="missing",], aes(x=years, y=abund, label="?"))
  # save_plot(plot = p7, filename = paste0("D:/Github/ICM/Figures/tuned/", i, "/Nat_M_", i, ".png"), base_width = 6,base_height = 4)
  # 
 
}


```


