---
output: word_document
editor_options: 
  chunk_output_type: console
---

```{r, prep-data,echo=F, message=F, warning=F, fig.width=6, fig.height=4,include=F,message=F}

if(load.results==F)
{
  Stocks <- ASR.long |> 
                      collapse::fsubset(!is.na(value)) |>
                      collapse::fgroup_by(Stock, type) |>
                      collapse::fsummarize(count=length(unique(value))) |>
                      collapse::fgroup_by(Stock) |>
                      collapse::fsummarize(types=length(unique(type))) |>
                      collapse::fsubset(types==5) |>
                      collapse::fselect(Stock)

  ASR.tmp <- ASR.long 
  ASR.tmp$age <- as.numeric(ASR.tmp$age)
  ASR.stocks <- ASR.tmp |> 
                          collapse::fsubset(Stock %in% Stocks$Stock) |>
                          collapse::fsubset(!is.na(value)) |>
                          collapse::roworder(Stock, Year, type, age)
                          
  # print(Stocks)
  Stocks <- Stocks$Stock
  
  # Going to remove Sebastes norvegicus because we can't get fecundity as the only data we have is total numbers.
  #Stocks <- Stocks[Stocks != "ICES-AFWG_DEEP1-2_Sebastes_norvegicus"]
  # Esmarki doesn't work great as it is assessed using a quarterly model.
  #Stocks <- Stocks[Stocks != "ICES-WGNSSK_NS 4-3aN_Trisopterus_esmarkii"]
  #i = 'ICES-AFWG_NEA1-2_Melanogrammus_aeglefinus'
  years.tmp <- NULL
  pnm.tmp <- NULL
  waa.tmp <- NULL
  ages.tmp <- NULL
  rem.tmp <- NULL
  mx.tmp <- NULL
  NE.tmp <- NULL
  vpa.tmp <- NULL
  am.tmp <- NULL
  #mr.tmp <- NULL
  abund.tmp <- NULL
  full.abund.tmp <- NULL
  full.rem.tmp <- NULL
  fs.tmp <- NULL
  for(i in Stocks)
  {
  print(i)
  ASR.sub <- ASR.long |>
    collapse::fselect(Year, Stock, type, age, value) |>
    collapse::fsubset(Stock==i)

  
    # Dropping the first 7 years as the 8 year olds are all missing
  if(i == "ICES-WGNSSK_NS  4-6a-20_Melanogrammus_aeglefinus") ASR.sub <- ASR.sub |> collapse::fsubset(Year >= 1972)
  # maxage <- max(as.numeric(ASR.sub$age[!is.na(ASR.sub$value)]))
  # maxYear <- max(ASR.sub$Year[!is.na(ASR.sub$value)])
  # minYear <- min(ASR.sub$Year[!is.na(ASR.sub$value)])
  # forplot <- ASR.sub[as.numeric(ASR.sub$age) < (maxage+1) & ASR.sub$Year %in% minYear:maxYear,]
  # 
  # # summary plots
  # print(ggplot() + geom_line(data=forplot, aes(Year, value)) + facet_grid(type~as.numeric(age), scales="free_y") +
  #         geom_vline(data=forplot[is.na(forplot$value),], aes(xintercept=Year), colour="red") + facet_grid(type~as.numeric(age), scales="free_y") +
  #         theme_bw() + 
  #         ggtitle(i)
  # )
  
  age.mat <- ASR.sub |> collapse::fsubset(type=="AM") |> dplyr::rename(AM=value) |> collapse::fselect(-type)
  # All of the age at maturities are NA in 0 and 1 year olds, so make them 0's, do that carefully just
  # in case that changes later...
  am.0s <- length(which((!is.na(age.mat$AM[age.mat$age ==0]))))
  am.1s <- length(which((!is.na(age.mat$AM[age.mat$age ==1]))))
  am.2s <- length(which((!is.na(age.mat$AM[age.mat$age ==2]))))
  if(am.0s == 0) age.mat$AM[age.mat$age ==0] <- 0
  if(am.1s == 0) age.mat$AM[age.mat$age ==1] <- 0
  if(am.2s == 0) age.mat$AM[age.mat$age ==2] <- 0
  
  #if(am.1s | am.0s | am.2s > 0) print("Stop, you need to check the age at maturity for either age 0 or 1 as there is data in there.")
  nat.mort <-  ASR.sub |> collapse::fsubset(type=="NM") |> dplyr::rename(NM=value) |> collapse::fselect(-type)
  abund <- ASR.sub |> collapse::fsubset(type=="Num") |> dplyr::rename(Num=value) |> collapse::fselect(-type)
  weight.age <- ASR.sub |> collapse::fsubset(type=="WA") |> dplyr::rename(WA=value) |> collapse::fselect(-type)
  if(i == Stocks[30]) weight.age$WA <- weight.age$WA/1000
  removals <- ASR.sub |> collapse::fsubset(type=="Catch") |> dplyr::rename(Catch=value) |> collapse::fselect(-type)

 # if(i=="ICES-WGBFAS_BS 22-32_Sprattus_sprattus") removals$Catch <- removals$Catch/1000
  
  data <- age.mat |>
    full_join(nat.mort) |>
    full_join(abund) |>
    full_join(weight.age) |>
    full_join(removals)

  # Aahh??  Is this NA dropping useful data, needed to quick fix the age at maturity data...
  data$available <- apply(is.na(data[, c("AM", "Num", "WA")]), 1, function(x) all(!x==T))
  data <- data[data$available==T,]

  # Tidy up the data for input...
  data$prop.nat.mort <- 1-exp(-data$NM)
  #prop.nat.mort[,-which(names(prop.nat.mort) %in% c("Year", "Stock", "type"))] <- 1-exp(-prop.nat.mort[,-which(names(prop.nat.mort) %in% c("Year", "Stock", "type"))])

  
  rem <- data |> collapse::fgroup_by(Year) |> collapse::fsummarize(rem=sum(Catch,na.rm=T)) #|> dplyr::pull(rem)
  #rem <- data |> dplyr::group_by(Year,.drop=F) |> collapse::fsummarize(rem=sum(Catch,na.rm=T)) #|> dplyr::pull(rem)
  
  # Never run, so not doing anything.
  # missing_rem<- NULL
  # if(any(is.na(rem$rem))) 
  # {
  #   missing_rem <- unique(data$Year)[which(is.na(rem$rem))]
  #   rem$rem[is.na(rem$rem)] <- median(rem$rem, na.rm=T)
  # }
  
  #rowSums(removals[,-which(names(removals) %in% c("Year", "Stock", "type"))], na.rm=T)
  years <- data |> dplyr::pull(Year) |> unique() |> sort()
  
  N.end <- sum(data[data$Year==max(years),]$Num)
  vpa.abund <- data |> dplyr::group_by(Year) |> dplyr::summarize(vpa=sum(Num,na.rm=T)) |> pull(vpa)

  # The real mx matrix, recruits produced per individual in each age class... Not perfect as I need to offset recruits/ssb, but close enough for the moment..
  #minage
  minage <- min(as.numeric(data$age))
  #maxage
  maxage <- max(as.numeric(data$age))
  #recruits
  annual <- data.frame(Year=data$Year[data$age==minage], recruits=data$Num[data$age==minage])
  #ssn
  data$ssn <- data$Num * data$AM
  #ssb
  data$ssb <- data$ssn * data$WA #I need to figure out how to line this up with the number of recruits for the right years in the data object.... got it right for the overall r.p.ssb below.
  #tot.ssb
  annual <- data |> group_by(Year) |> summarize(tot.ssb = sum(ssb)) |> left_join(annual)
  
  #tst <- data |> group_by(Year) |> summarize(tot.ssn = sum(ssn)) |> left_join(annual)

  #r.p.ssb This needs to be offset by the age of recruits. So here's my lining this up logic.  For age 0, we get
  # the recruit and SSB estimates from the same survey, thus these age 0 recruits will have been produced by the SSB in the previous year...
  # So the R in 1970 were produced by SSB in 1969 when min age =0
  # If min.age = 1 then R in 1970 is produced by SSB in 1968... and so on.
  # FIX 1 "Recruit year" = SSB year + min.age + 1 (or min.age +2 as SSB.year is the first column)
  # Now for RPS there's another wrinkle because of this, because our model is N(1970) = lambda * N(1969) and lambda is made up of lx and mx
  # so if the recruits show up in 1970, the fecundity term that gets us there (irrespective of the age offset) has to be for 1969, becuase
  # that gets us to the babies that show up in 1970
  # FIX 2 So "RPS year, recs.per.age year, and mx year" = SSB year + min.age
  # I believe this to be correct, but we all need to discuss this to make sure the logic holds.
  annual$r.p.ssb <- c(rep(NA,minage),annual$recruits[(minage+2):nrow(annual)]/annual$tot.ssb[1:(nrow(annual)-minage-1)],NA)
  # recs.per.age
  data <- left_join(data, annual)
  # So I need to make an offset SSB in the 'data' object to line up with the correct r.p.ssb field.  This is probably gonna suck...
  tmp <- NULL
  for(j in 1:length(years))
  {
    tst <- data|> collapse::fsubset(Year == years[j]) |> collapse::fselect(ssb,ssn,Year,age)
    tst$Year <- tst$Year + minage # We want this to line up the the RPS year, so just adding minage here.
    names(tst) <- c("ssb.offset","ssn.offset","Year","age")
    tmp[[j]] <- tst
  }
  # Unpack the list
  ssb.off <- do.call('rbind',tmp)
  # And merge it with the data object
  data <- left_join(data,ssb.off,by=c("Year","age"))
  data$recs.per.age <- data$ssb.offset*data$r.p.ssb
  # mx
  # Some of the stocks are just the males and females, so these are already half the population.  Probably can just not include the male stocks in the end.
  # No longer dividing by 2 because we should really divide recruits and ssn by 2 to be female only, but that's pointless so we roll along with this.
  data$mx <- data$recs.per.age/data$ssn.offset # if(grepl("males",i)) 
  #if(!grepl("males",i))data$mx <- data$recs.per.age/data$ssn.offset/2 # Moms only! 
  data$mx[is.nan(data$mx)] <- 0 # if we don't have any spawners in an age class in a year their fecundity is 0
  # Easier to remove the years where we don't have recs.per.age...
  #data <- data |> collapse::fsubset(Year %in% years[(minage+1):length(years)])
  # Something is wrong with the decline rate method, but the exponential and logistic are working pretty... pretty... pretty good...
  
  age.mat <- data |> collapse::fselect("Year", "age", "AM") |> 
                     pivot_wider(names_from=age, values_from = AM) |> collapse::fselect(-Year)
  prop.nat.mort <- data |> collapse::fselect("Year", "age", "prop.nat.mort") |> 
                            pivot_wider(names_from=age, values_from = prop.nat.mort) |> 
                            collapse::fselect(-Year) |> as.data.frame()
  
  weight.age <- data |> collapse::fselect("Year", "age", "WA") |> pivot_wider(names_from=age, values_from = WA) |> collapse::fselect(-Year)
  mx <- data |> collapse::fselect("Year", "age", "mx") |> 
                 pivot_wider(names_from=age, values_from = mx) |> 
                 collapse::fselect(-Year) |> as.data.frame()
  # Get the abundance matrix
  abund.age <- data |> collapse::fselect("Year", "age", "Num") |> 
                        pivot_wider(names_from=age, values_from = Num) |> 
                        collapse::fselect(-Year) |> as.data.frame()
  
  # Now we can save out the catch and get an instantaneous F
    data$Catch[is.na(data$Catch)] <- 0
    data$Exp <- data$Catch/data$Num 
    # If it is exactly 1 that leads to an Inf, which is annoying, so make it 1.1 and fix it with the rest below
    data$Exp[data$Exp == 1] <- 1.1
    # And make this an F
    data$Fs <- -log(1-data$Exp)
    if(any(is.na(data$Fs)))
    {
      fixers <- which(is.na(data$Fs))
      print(paste0("Had to replace ",length(fixers), ' exploitation rates for stock ',i))
      for(f in fixers)
      {
        yr <- data$Year[f]
        fs <- max(data$Fs[data$Year == yr],na.rm=T)
        data$Fs[f] <- fs
        data$Exp[f] <- 1-exp(-fs)
      }
    }
  
  full.rems <- data |> collapse::fselect("Year", "age", "Catch") |> pivot_wider(names_from=age, values_from = Catch) |> collapse::fselect(-Year)
  full.Fs <-  data |> collapse::fselect("Year", "age", "Fs") |> pivot_wider(names_from=age, values_from = Fs) |> collapse::fselect(-Year)
    
    
    if(i == "DFO_2J3KL_Gadus_morhua")
    {
      age.mat[,8:10] <- 1
      prop.nat.mort[,8:10] <- prop.nat.mort[,7]
      weight.age[12:14,9:10] <- weight.age[12:14,8]
      weight.age[15,10] <- weight.age[15,9]
      mx[12:16,9:10] <- mx[12:16,8]
      mx[17,10] <- mx[17,9]
      full.Fs[12:14,9:10] <- full.Fs[12:14,8]
      full.Fs[15,10] <- full.Fs[15,9]
      abund.age[12:14,9:10] <- abund.age[12:14,8]
      abund.age[15,10] <- abund.age[15,9]
      # I could calculate, but this will get us to the same place...
      full.rems[12:14,9:10] <- full.rems[12:14,8]
      full.rems[15,10] <- full.rems[15,9]
    }
    
    if(i == "DFO_4T-Spring_Clupea_harengus")
    {
      age.mat[6:7,10] <- 1
      prop.nat.mort[6:7,10] <- prop.nat.mort[6:7,9]
      weight.age[6:7,10] <- weight.age[6:7,9]
      mx[6:9,10] <- mx[6:9,9]
      full.Fs[6:7,10] <- full.Fs[6:7,9]
      abund.age[6:7,10] <- abund.age[6:7,9]
      full.rems[6:7,10] <- full.rems[6:7,9]
    }
    
    if(i == "ICES-HAWG_CS 6a- 7b-7c_Clupea_harengus") 
    {
      age.mat[30,8] <- 1
      prop.nat.mort[30,8] <- prop.nat.mort[30,7]
      weight.age[30,8] <- weight.age[29,8]
      mx[30:31,8] <- mx[30:31,9]
      full.Fs[30,8] <- full.Fs[30,7]
      abund.age[30,8] <- abund.age[30,7]
      full.rems[30,8] <- full.rems[30,7]
    }
    
    if(i == "ICES-WGCSE_IS6a-7b-7j_Dicentrarchus _labrax")
    {
      age.mat[c(14,27,40),5] <- age.mat[1,5]
      prop.nat.mort[c(14,27,40),5] <- prop.nat.mort[1,5]
      weight.age[c(14,27,40),5] <- weight.age[c(13,26,39),5]
      mx[c(14,16,27,29,40,42),5] <- mx[c(14,16,27,29,40,42),6]
      full.Fs[c(14,27,40),5] <- full.Fs[c(14,27,40),4]
      abund.age[c(14,27,40),5] <- abund.age[c(14,27,40),4]
      full.rems[c(14,27,40),5] <- full.rems[c(14,27,40),4]
    }
    # Clear out some 0's...
    if( i == "AFSC_EEBSAI_Limanda_aspera")
    {
      mx[5,18] <- mean(unlist(mx[5,c(17,19)]))
      mx[c(6,8),19] <- mx[c(6,8),18]
      mx[2:7,20] <- mx[2:7,19] 
    }
  

  
  # I had filled the years with no SSB data to inform them.  instead I'm going to remove those years...
  
  
   if(minage >0) 
  {
    rm <- -(1:minage)
    years <- years[rm]
    prop.nat.mort <- prop.nat.mort[rm,]
    weight.age <- weight.age[rm,]
    rem <- rem[rm,]
    mx <- mx[rm,]
    vpa.abund <- vpa.abund[rm]
    age.mat <- age.mat[rm,]
    abund.age <- abund.age[rm,]
    full.Fs <- full.Fs[rm,]
    full.rems <- full.rems[rm,]
   }
  #   mx.fill <- as.data.frame(matrix(rep(colMeans(mx,na.rm=T),minage),nrow=minage,byrow=T),colnames = names(mx))
  #   names(mx) <- names(mx.fill)
  #  # mx <- rbind(mx[(minage+1):nrow(mx),],mx.fill) # or is it
  #   mx <- rbind(mx.fill,mx[(minage+1):nrow(mx),]) # I think this is right!
  # }
  
  
    years.tmp[[i]] <- years
    pnm.tmp[[i]] <- prop.nat.mort
    waa.tmp[[i]] <- weight.age
    ages.tmp[[i]] <- minage:maxage
    rem.tmp[[i]] <- rem
    mx.tmp[[i]] <- mx
    NE.tmp[[i]] <- N.end
    vpa.tmp[[i]] <- vpa.abund
    am.tmp[[i]] <- age.mat
    #mr.tmp[[i]] <- missing_rem
    abund.tmp[[i]] <- abund.age
    fs.tmp[[i]] <- full.Fs
    full.rem.tmp[[i]] <- full.rems
  } #end input data loop
  
  save(years.tmp,pnm.tmp,waa.tmp,ages.tmp,rem.tmp,mx.tmp,NE.tmp,vpa.tmp,mr.tmp,
       am.tmp,Stocks,ASR.stocks,ASR.long,abund.tmp,fs.tmp,full.rem.tmp,
       file =  paste0(loc,"/Results/model_inputs_no_age_correction.Rdata"))
  
  } # end load results
```
  
   
  So now I can try to do some tuning, both forwards and backwards, lets see what we get from that...
  
```{r tunes,include=F,echo=F,warning=F,message=F}
  
  
  ########################## Now run the tuning sims
  #
  
  if(load.results==F)
  {
  load(file = paste0(loc,"/Results/model_inputs_no_age_correction.Rdata"))
  
  for.tune.all.res <- NULL
  for.tune.summary <- NULL
  for(i in Stocks)
  {
    years <- years.tmp[[i]]
    prop.nat.mort <- pnm.tmp[[i]] 
    #rem <- rem.tmp[[i]] 
    mx <- mx.tmp[[i]] 
    N.end <- NE.tmp[[i]] 
    ages <- ages.tmp[[i]]
    vpa.abund <- vpa.tmp[[i]] 
    abund <- abund.tmp[[i]]
    fs <-fs.tmp[[i]]
    full.rem <- rem.tmp[[i]]
    #full.abund <- full.abund.tmp[[i]]
    #all.abund <- full.abund.tmp[[i]]
    #N.end <- vpa.abund[length(vpa.abund)]
    #Pick your step size
    ss.size <- 0.005
    sensistive.stocks <- c("AFSC_GOA_Theragra_chalcogramma",
                            "DFO_2J3KL_Gadus_morhua",
                            "DFO_3Pn-4RS_Gadus_morhua",
                            "DFO_4T-4VN_Gadus_morhua",
                            "DFO_4T_Scomber_scombrus",
                            "ICES-AFWG_NEA1-2_Melanogrammus_aeglefinus",
                            "ICES-AFWG_NEA1-2_Gadus_morhua",
                            "ICES-HAWG_NS_Ammodytes_dubius",
                            "ICES-NWWG_FA5b_Pollachius_virens",
                            "ICES-NWWG_FAPL5b1_Gadus_morhua",
                            "ICES-WGBFAS_BS 22-32_Sprattus_sprattus",
                            "ICES-WGCSE_IS7a_Gadus_morhua",
                            "ICES-WGCSE_CS7a_Merlangius_merlangus",
                            "ICES-WGCSE_CS7e-k_Gadus_morhua",
                            "ICES-WGCSE_CS27.6a_Merlangius_merlangus",
                            "ICES-WGHANSA_SP8abd_Sardina _pilchardus", 
                            "ICES-WGNSSK_NS 4-7d,20_Gadus_morhua",
                            "ICES-WGNSSK_NS  4-6a-20_Melanogrammus_aeglefinus",
                            "ICES-WGNSSK_NS 4-7d_Merlangius_merlangus",
                            "ICES-WGNSSK_NS 4-3aN_Trisopterus_esmarkii",
                            "NEFSC-GARMIII_SNE- MA_Limanda_ferruginea",
                            "NEFSC-GARMIII_MA_Paralichthys_dentatus",
                            "NEFSC-GARMIII_5Y_Melanogrammus_Aeglefinus",
                            "NEFSC_NWA_Scomber _scombrus")
    
  #NE Arctic aeglefinus (high and lows)  (21) solved
  #Faroes 5b P. virens (high and lows)  (29) solved
    
    if(i %in% sensistive.stocks) ss.size = ss.size/10
  
     N.start <- vpa.abund[1]
     print(i)
     # The fecundities are 
     fast.for.tune <- fast.tunes(years,
                             tuner=what.2.tune,
                             step.size = ss.size, 
                             abund.ts = vpa.abund,
                             ages=ages,
                             nm = -(log(1-prop.nat.mort)),
                             fecund = mx,
                             fm = fs,
                             abund.age = abund, 
                             catch.age = full.rem, 
                             N.init = N.start,
                             direction= 'forwards'
                             )
     
     for.tune.all.res[[i]] <- fast.for.tune
     for.tune.tmp <- data.frame(fast.for.tune$res,Stock = i)
     for.tune.summary[[i]] <- for.tune.tmp
  }
 
  saveRDS(for.tune.summary,paste0(loc,"/Results/forwards_fully_tuned_summary_no_age_correction_",what.2.tune,".Rds"))
  saveRDS(for.tune.all.res,paste0(loc,"/Results/forwards_fully_tuned_all_no_age_corection_res_",what.2.tune,".Rds"))
  # 
}# end if load results


```

```{r paper-other-metrics-and-metadata,echo=F,include=F,warning=F,message=F}

if(load.results==F)
{
  # We are now looking at everything, lifetime reproductive success
  
  for.tune.summary <- readRDS(paste0(loc,"/Results/forwards_fully_tuned_summary_no_age_correction_",what.2.tune,".Rds"))
  for.tune.all <- readRDS(paste0(loc,"/Results/forwards_fully_tuned_all_no_age_corection_res_",what.2.tune,".Rds"))
  
  
  load(file =  paste0(loc,"/Results/model_inputs_no_age_correction.Rdata"))
  # Get the stocks...
  Stocks <- names(for.tune.summary)
  n.stocks <- length(Stocks)
  
  
  ############ Meta data and clean up, could be it's own chunk really, but it's really fast, so meh...
  
  #  A quick way to get the other potentially interesting info for the stock...
  drop <- which(names(ASR.long) %in% c("Year","type","age","value"))
  meta <- NULL
  for(i in Stocks) 
  {
    meta[[i]] <- ASR.long[ASR.long$Stock == i,-drop][1,]
    meta[[i]]$age.min <- min(ages.tmp[[i]])
    meta[[i]]$age.max <- max(ages.tmp[[i]])
  }
  meta <- do.call('rbind',meta)
  
  # First making a meta data object and adding a bunch of columns to it... very messy!!
  meta$Species[meta$Species == ' harengus']  <- "harengus"
  meta$Species[meta$Species == "Aeglefinus"] <- "aeglefinus"
  meta$Species[meta$Species == "Solea"] <- "solea"
  meta$Genus[meta$Genus == " Hippoglossoides"] <- "Hippoglossoides"
  meta$G.short <- toupper(paste0(substr(meta$Genus,1,1),"."))
  meta$G.Species <- paste0(meta$G.short," ",meta$Species)
  # Simplified Management
  meta$Manage.short <- meta$Management
  meta$Manage.short[grep("TRAC",meta$Management)] <- "DFO-TRAC"
  meta$Manage.short[grep("DFO",meta$Management)] <- "DFO-TRAC"
  meta$Manage.short[grep("NEFSC",meta$Management)] <- "NEFSC"
  meta$Manage.short[grep("ICES",meta$Management)] <- "ICES"
       
  # The 3 pieces of the ocean
  meta$LME <- "NW Atlantic"
  meta$LME[meta$Management == "AFSC"] <- "Pacific (Alaska)"
  meta$LME[grepl("ICES",meta$Management)] <- "NE Atlantic"
  # Some other Area summaries
  meta$Area.broad <- meta$Area
  meta$Area.long <- meta$Area
  meta$Area.narrow <- "" # Leave this blank if not needed
       
  meta$Area.broad[grep("NS",meta$Area)] <- "NS"
  meta$Area.long[grep("NS",meta$Area)] <- "North Sea"
  meta$Area.broad[grep("CS",meta$Area)] <- "CS"
  meta$Area.long[grep("CS",meta$Area)] <- "Celtic Sea"
  meta$Area.broad[grep("ROCK6b",meta$Area)] <- "CS"
  meta$Area.long[grep("ROCK6b",meta$Area)] <- "Celtic Sea Rockall"
  meta$Area.broad[grep("IS",meta$Area)] <- "IS"
  meta$Area.long[grep("IS",meta$Area)] <- "Irish Sea"
  meta$Area.broad[grep("BS",meta$Area)] <- "BS"
  meta$Area.long[grep("BS",meta$Area)] <- "Baltic Sea"
  meta$Area.broad[grep("NEA",meta$Area)] <- "NEA"
  meta$Area.long[grep("NEA",meta$Area)] <- "NE Arctic"
  meta$Area.broad[grep("B28.1",meta$Area)] <- "BS"
  meta$Area.long[grep("B28.1",meta$Area)] <- "Baltic Sea"
  meta$Area.broad[grep("SP8abd",meta$Area)] <- "BoB"
  meta$Area.long[grep("SP8abd",meta$Area)] <- "Bay of Biscay"
  meta$Area.broad[grep("FA",meta$Area)] <- "I-F"
  meta$Area.broad[grep("ICE",meta$Area)] <- "I-F"
  meta$Area.long[grep("FA",meta$Area)] <- "Faroes"
  meta$Area.long[grep("ICE",meta$Area)] <- "Iceland"
  
  meta$Area.broad[grep("GOM",meta$Area)] <- "GOM-GB"
  meta$Area.long[grep("GOM",meta$Area)] <- "Gulf of Maine"
  meta$Area.broad[grep("GB",meta$Area)] <- "GOM-GB"
  meta$Area.long[grep("GB",meta$Area)] <- "Georges Bank"
  meta$Area.broad[grep("5Y",meta$Area)] <- "GOM-GB"
  meta$Area.long[grep("5Y",meta$Area)] <- "NAFO 5Y"
  meta$Area.broad[grep("5Z",meta$Area)] <- "GOM-GB"
  meta$Area.long[grep("5Z",meta$Area)] <- "NAFO 5Z"
  meta$Area.broad[grep("USATL",meta$Area)] <- "GOM-GB" # The fishery is broader than just GOM, but it does also include it.
  meta$Area.long[grep("USATL",meta$Area)] <- "US Atlantic" # The fishery is broader than just GOM, but it does also include it.
  meta$Area.broad[grep("NWA",meta$Area)] <- "GOM-GB" # Mackerel... so that definition is a bit narrow....
  meta$Area.long[grep("NWA",meta$Area)] <- "US Atlantic" # Mackerel... so that definition is a bit narrow....
  #meta$Area1[grep("SNE- MA",meta$Area)] <- "GOM-GB" # YT in US, so no GB so that definition is a bit narrow....
  meta$Area.broad[grep("MA",meta$Area)] <- "GOM-GB" # YT  and summer flounder in US, so no GB so that definition is a bit narrow....
  meta$Area.long[grep("MA",meta$Area)] <- "Gulf of Maine" # YT  and summer flounder in US, so no GB so that definition is a bit narrow....
  meta$Area.broad[grep("BSAI",meta$Area)] <- "BSAI"
  meta$Area.broad[grep("4T",meta$Area)] <- "GSL"
  meta$Area.long[grep("4T",meta$Area)] <- "NAFO 4T"
  meta$Area.broad[grep("2J3",meta$Area)] <- "NFLD"
  meta$Area.long[grep("2J3",meta$Area)] <- "NFLD"
  meta$Area.broad[grep("3Pn-4RS",meta$Area)] <- "NFLD"
  meta$Area.long[grep("3Pn-4RS",meta$Area)] <- "NFLD"
  meta$Area.long[grep("GOA",meta$Area)] <- "Gulf of Alaska"
  meta$Area.long[grep("AI",meta$Area)] <- "Aleutian Islands"
  meta$Area.long[grep("ESB",meta$Area)] <- "Bering Sea"
  meta$Area.long[grep("BSAI",meta$Area)] <- "Bering Sea & AI"
  meta$Area[grep("BASI-Females",meta$Area)] <- "BSAI-Females"
  meta$Area.long[grep("BSAI-Females",meta$Area)] <- "Bering Sea & AI"
  meta$Area.narrow[meta$Stock == "ICES-NWWG_FA5b_Pollachius_virens"] <- "5b"
  meta$Area.narrow[meta$Stock == "ICES-NWWG_FA5a_Pollachius_virens"] <- "5a"
  meta$Area.narrow[meta$Stock == "ICES-WGNSSK_NS4 _Solea_solea"] <- "4"
  meta$Area.narrow[meta$Stock == "ICES-WGNSSK_NS 7d._Solea_solea"] <- "7d"
  meta$Area.narrow[meta$Stock == "ICES-WGBFAS_NS IIIa 22-24_Solea_Solea"] <- "22-24"
  meta$Area.narrow[meta$Stock == "ICES-WGNSSK_NS 7d_Pleuronectes_platessa"] <- "7d"
  meta$Area.narrow[meta$Stock == "ICES-WGNSSK_NS 4,20_Pleuronectes_platessa"] <- "4 20"
  meta$Area.narrow[meta$Stock == "ICES-WGCSE_IS7e_Pleuronectes_platessa"] <- "7e"
  meta$Area.narrow[meta$Stock == "ICES-WGCSE_IS27.7a_Pleuronectes_platessa"] <- "7a"
  meta$Area.narrow[meta$Stock == "ICES-NWWG_FA5b_Melanogrammus_aeglefinus"] <- "5b"
  meta$Area.narrow[meta$Stock == "ICES-NWWG_ICE5a_Melanogrammus_aeglefinus"] <- "5a"
  meta$Area.narrow[meta$Stock == "ICES-WGBFAS_B28.1_Clupea_harengus"] <- "28"
  meta$Area.narrow[meta$Stock == "ICES-WGBFAS_BS 25-29-32_Clupea_harengus" ] <- "25-32"
  meta$Area.narrow[meta$Stock == "ICES-HAWG_WBS 22-24_Clupea_harengus"] <- "22-24"
  meta$Area.narrow[meta$Stock == "DFO_4T-Fall_Clupea_harengus"] <- "Fall"
  meta$Area.narrow[meta$Stock == "DFO_4T-Spring_Clupea_harengus"] <- "Spring"
  meta$Area.narrow[meta$Stock == "ICES-WGCSE_CS27.6a_Merlangius_merlangus"] <- "27.6a"
  meta$Area.narrow[meta$Stock == "ICES-WGCSE_CS7a_Merlangius_merlangus"] <- "7a"
  meta$Area.narrow[meta$Stock == "ICES-NWWG_ICE5a_Gadus_morhua"] <- "5a"
  meta$Area.narrow[meta$Stock == "ICES-NWWG_FAPL5b1_Gadus_morhua" ] <- "5b"
  meta$Area.narrow[meta$Stock == "ICES-WGNSSK_NS 4-7d,20_Gadus_morhua"] <- "4-7 20"
  meta$Area.narrow[meta$Stock == "ICES-WGCSE_NS6a_Gadus_morhua"] <- "6a"
  meta$Area.narrow[meta$Stock == "DFO_2J3KL_Gadus_morhua"] <- "2J 3KL"
  meta$Area.narrow[meta$Stock == "DFO_3Pn-4RS_Gadus_morhua"] <- "3Pn 4RS"
  meta$Area.narrow[meta$Stock == "NEFSC-CERT-TRAC_GB _Gadus_morhua"] <- "East"
  
  meta$Stock.short <- paste0(meta$Area.long," ",meta$Area.narrow," ",meta$G.short," ",meta$Species)
  meta$Stock.no.species <- paste0(meta$Area.long," ",meta$Area.narrow)

  
  for.tune.stocks <- NULL
  fta <- NULL
  
  # Going to rename these female stocks.
  fem.names <- c("AFSC_BASI-Females_Pleuronectes_quadrituberculatus",
                    "AFSC_EEBSAI-Females_Lepidopsetta_polyxystra",
                    "AFSC_BSAI-females_Atheresthes_stomais")
  fem.rename <- c("AFSC_BSAI_Pleuronectes_quadrituberculatus",
                    "AFSC_EEBSAI_Lepidopsetta_polyxystra",
                    "AFSC_BSAI_Atheresthes_stomais")
  # Going to drop these stocks
  dont <- paste(c("Mles","Males","COASTNOR"),collapse = "|")
  
  meta.sub <- NULL
  for(i in Stocks) 
  {
    org.nam <- i
    tmp <- for.tune.summary[[org.nam]]
    new.stock.nam <- org.nam
    # Don't bother for these stocks...
    if(!grepl(dont,tmp$Stock[1]))
    {
      # Grab the metadata and add in some new useful things...
      meta.sub[[i]] <- meta[meta$Stock == org.nam,]
        
      # Rename the ladies
      if(tmp$Stock[1] == fem.names[1]) new.stock.nam <- tmp$Stock <- fem.rename[1]
      if(tmp$Stock[1] == fem.names[2]) new.stock.nam <- tmp$Stock <- fem.rename[2]
      if(tmp$Stock[1] == fem.names[3]) new.stock.nam <- tmp$Stock <- fem.rename[3]
      
      meta.sub[[i]]$Stock <- new.stock.nam
      tmp <- data.frame(tmp,meta.sub[[i]])
      # For tunes all
      fta[[new.stock.nam]] <- for.tune.all[[org.nam]]
      fta[[new.stock.nam]]$meta <- meta.sub[[i]]
      for.tune.stocks[[new.stock.nam]] <- tmp
    }# End skip stocks...
  }
  # Now unpack them...
  for.tunes <- do.call("rbind",for.tune.stocks)
  for.tune.all <- fta
  meta.sub <- do.call("rbind",meta.sub)
  
  ######################### End Meta data and clean up #####################
  
  
  # Now some summaries...
  
  # Reset on the stocks...
  Stocks <- sort(names(for.tune.all))
  n.stocks <- length(Stocks)

  
  # Doubling time, no fishing
  dt.res <- NULL
  n.dt.sims <- 1000 # Increase to 1000 for final run, which takes like a full day or something 
  n.years <- 100
  for(i in Stocks)
  {
    str.time <- Sys.time()
    try <- for.tune.all[[i]]
    meta.tmp <- try$meta
    age.4.sim <- meta.tmp$age.min:meta.tmp$age.max
    double.time <- NA
    pop <- 1000
    tmp.res <- NULL
  for(s in 1:n.dt.sims)
  {
    
    tmp <- rep(0,n.years)
    for(y in 2:n.years)
    {
      
      # Get our sample for this run
      f.pick <- sample(nrow(try$fecund.opt),size=1)
      nm.pick <- sample(nrow(try$nm.opt),size=1)
      fec.samp <- try$fecund.opt[f.pick,]
      # This is instantaneous rate, which is what the Lotka function is expected (it is set up expecting instantaneous)
      nm.samp <- try$nm.opt[nm.pick,] 
      # now put these into Euler-lotka to get an r estimate
      res <- simple.lotka.r(mort = nm.samp,fecund=fec.samp,ages=age.4.sim)
      r.val <- res$res$r
      # If r is > 5 (lambda = exp(5)) it generally means the simple.lotka didn't converge (bad combo of fec and nm)
      # So we'll need to resample them until it is < 5
      while(r.val >= 5)
      {
        print("Resampling due to bat shit r value")
        f.pick <- sample(nrow(try$fecund.opt),size=1)
        nm.pick <- sample(nrow(try$nm.opt),size=1)
        fec.samp <- try$fecund.opt[f.pick,]
        # This is instantaneous rate, which is what the Lotka function is expected (it is set up expecting instantaneous)
        nm.samp <- try$nm.opt[nm.pick,] 
        # now put these into Euler-lotka to get an r estimate
        res <- simple.lotka.r(mort = nm.samp,fecund=fec.samp,ages=age.4.sim)
        r.val <- res$res$r
      } # end while loop
      pop[y] <- exp(r.val)*pop[y-1]
      if(pop[y] >= 2*pop[1] & tmp[y] == 0) tmp[y:n.years] <- 1
    } # end the years loop
    tmp.res[[s]] <- data.frame(year =1:n.years,doubled = tmp,sim=s)
    
    } # end sim loop
    res.tmp <- do.call("rbind",tmp.res)
    
  dt.res[[i]] <- data.frame(res.tmp,meta.tmp)
  count <- 0
  print(paste0("Stock ",i," Sim ", s," time =", round(Sys.time()-str.time,digits=1)," minutes Stock number",count+1))
  } # end Stocks loop
  
  dub.time <- do.call("rbind",dt.res)
  
  dub.time.summary <- dub.time |> collapse::fgroup_by(Stock,year)  |> collapse::fsummarise(prop = sum(doubled)/n.dt.sims)
  dub.time.summary <- left_join(dub.time.summary,meta.sub,by="Stock")
  
  # Now to get generation lengths + reproductive rates....
  # First I need to get the fecundity and natural mortalities by cohort instead of year.
  res.fin <- NULL
  res.year.fin <- NULL
  res.lambda.fin <- NULL
  for(i in Stocks) # 
  {
    tst <- for.tune.all[[i]]
    meta.tmp <- tst$meta
    # Fishing mortality
    fm.org.tmp <- tst$fm.org
    fm.tmp <- tst$fm.opt
    # fecundity
    fec.tmp <- tst$fecund.opt
    fec.org.tmp <- tst$fecund.org
    # Natural mortality
    m.org.tmp <- exp(-tst$nm.org) # This is survivorship
    m.tmp <- exp(-tst$nm.opt) # This is survivorship
    # Total mortality
    z.tmp <- exp(-tst$z.opt) # This is survivorship
    z.org.tmp <- exp(-tst$nm.org -fm.org.tmp) # This is survivorship
    
    ages <- meta.tmp$age.min:meta.tmp$age.max
    n.ages <- length(ages)
    years <- tst$res$year
    n.years <- length(years)
    # Now I need to grab the fecundities and nat morts by cohort
    if(n.years > n.ages)
    {
    res.cohort <- NULL
    res.year <- NULL
    res.lambda <- NULL
    for(y in 1:(n.years-n.ages+1))
    {
      count = 0
      fs <- NA
      # The lx is no fishing survivorship, zx I'm calling the survivorship including fishing
      lx <- lx.org <- lx.year <- zx <- zx.org <- zx.year <- 1
      fs.org <- NA
      
      for(a in 1:n.ages)
      {
      fs[a] <- fec.tmp[y+count,a]  
      fs.org[a] <- fec.org.tmp[y+count,a]  
      if(a > 1) 
      {
        # No fishing
        lx[a] <- lx[a-1] * m.tmp[y+count,a]  
        lx.org[a] <- lx.org[a-1]* m.org.tmp[y+count,a]  
        lx.year[a] <- lx.year[a-1] * m.tmp[y,a]
        # Including fishing
        zx[a] <- zx[a-1] * z.tmp[y+count,a]  
        zx.org[a] <- zx.org[a-1]* z.org.tmp[y+count,a]  
        zx.year[a] <- zx.year[a-1] * z.tmp[y,a]
      }  # end the a > 1 if
          count <- count + 1
      }# end the ages loop
          res.cohort[[y]] <- data.frame(mx.opt = fs,lx.opt = lx,mx.org = fs.org,lx.opt = lx,
                                 mx.lx.opt = fs*lx,mx.lx.org = fs.org*lx.org,
                                 x.mx.lx.opt = fs*lx*ages,x.mx.lx.org = fs.org*lx.org*ages,
                                 zx.opt = zx,zx.opt = zx,
                                 mx.zx.opt = fs*zx,mx.zx.org = fs.org*zx.org,
                                 x.mx.zx.opt = fs*zx*ages,x.mx.zx.org = fs.org*zx.org*ages,
                                 cohort=years[y],age = ages,meta.tmp)
          
          res.year[[y]] <- data.frame(mx.opt = unlist(fec.tmp[y,]),lx.opt = lx.year,
                                 mx.lx.opt = unlist(fec.tmp[y,])*lx.year,
                                 x.mx.lx.opt = unlist(fec.tmp[y,])*lx.year*ages,
                                 zx.opt = zx.year,
                                 mx.zx.opt = unlist(fec.tmp[y,])*lx.year,
                                 x.mx.zx.opt = unlist(fec.tmp[y,])*lx.year*ages,
                                 age = ages,year=years[y],meta.tmp)
  
    } # end the years loop
  
  # Do a years loop to get lambda with no fishing for each year, rather than by cohort...
    for(yy in 1:(n.years-1))
    {
      nm <- as.numeric(tst$nm.opt[yy,])
      z <- as.numeric(tst$z.opt[yy,])
      fec <- as.numeric(tst$fecund.opt[yy,])
      nm.init <- as.numeric(tst$nm.org[yy,])
      fec.init <- as.numeric(tst$fecund.org[yy,])
      z.init <- as.numeric(tst$z.org[yy,])
      lam.no.fish <- exp(simple.lotka.r(mort = nm,fecund = fec,ages=ages)$res$r)
      lam.fish <- exp(simple.lotka.r(mort = z,fecund = fec,ages=ages)$res$r)
      lam.org.no.fish <- exp(simple.lotka.r(mort = nm.init,fecund = fec.init,ages=ages)$res$r)
      lam.org.fish <- exp(simple.lotka.r(mort =  z.init,fecund = fec.init,ages=ages)$res$r)
      
      # Now summarize these
      res.lambda[[yy]] <-  data.frame(lam.no.fish = lam.no.fish,lam.fish = lam.fish,
                                      lam.org.no.fish = lam.org.no.fish,
                                      lam.org.fish = lam.org.fish,
                                      year=years[yy],meta.tmp)
    } # End the yy loop to get the lambdas...
  # unpack it...
  res.fin[[i]] <- do.call('rbind',res.cohort)
  res.year.fin[[i]] <- do.call('rbind',res.year)
  res.lambda.fin[[i]] <-  do.call('rbind',res.lambda)
  }  # end if to make sure we have enough data to get the cohort estimates.
  
  }# end the stock loop
  
  res.cohort.final <- do.call('rbind',res.fin)
  res.year.final <- do.call('rbind',res.year.fin)
  res.lambda.final <- do.call('rbind',res.lambda.fin)
  
  pop.dam <- res.cohort.final |> dplyr::group_by(cohort,Stock) |> dplyr::summarise(gen.len.opt = sum(x.mx.lx.opt)/sum(mx.lx.opt),
                                                                  gen.len.org = sum(x.mx.lx.org)/sum(mx.lx.org),
                                                                  R0.opt = sum(mx.lx.opt),R0.org = sum(mx.lx.org))
  pop.dam <- left_join(pop.dam,meta.sub,by="Stock")
  
  dub.time.summary <- data.frame(dub.time.summary)
  pop.dam <- data.frame(pop.dam)
  # saveRDS(pop.dam,paste0("D:/Github/ICM/Results/R0_and_gen_length_",what.2.tune,".Rds"))
  # saveRDS(dub.time.summary,paste0("D:/Github/ICM/Results/doubling_time_",what.2.tune,".Rds"))
  # saveRDS(for.tunes,paste0("D:/Github/ICM/Results/forward_tunes_for_figures_",what.2.tune,".Rds"))
  save(dub.time.summary,pop.dam,res.year.final,res.cohort.final,for.tunes,dub.time,for.tune.all,res.lambda.final,meta,meta.sub,
       file=paste0(loc,"/Results/all_cleaned_forward_tune_summaries_no_age_corection_",what.2.tune,".Rdata"))
  
  write.csv(meta.sub, paste0(loc,"/Data/metadata_no_age_corection.csv"))
} # end if load results
```




```{r simp-figs,include=F,echo=F,message=F,warning=F}
load(file=paste0(loc,"/Results/all_cleaned_forward_tune_summaries_no_age_corection_",what.2.tune,".Rdata"))
res.lambda.fin <- data.frame(res.lambda.final)

six.species <- c('morhua','harengus','aeglefinus','virens','solea','platessa')
pop.dam.6 <- pop.dam |> collapse::fsubset(Species %in% six.species)
for.tunes.6 <- for.tunes |> collapse::fsubset(Species %in% six.species)
dub.time.6 <- dub.time.summary |> collapse::fsubset(Species %in% six.species)
res.lambda.fin$decade <- floor(res.lambda.fin$year/10)*10
res.lambda.fin <- res.lambda.fin |> collapse::fgroup_by(Stock,decade) |> collapse::fmutate(mn.lam = mean(lam.fish,na.rm=T),
                                                                                 med.lam = median(lam.fish,na.rm=T),
                                                                                 sd.lam = sd(lam.fish,na.rm=T))
res.lambda.fin <- res.lambda.fin |> collapse::fgroup_by(Species,decade) |> collapse::fmutate(lm.spec.mn = mean(mn.lam,na.rm=T))              
res.lambda.fin <- res.lambda.fin |> collapse::fgroup_by(Stock) |> 
                                                          collapse::fmutate(lam.no.fish.mn = mean(lam.no.fish,na.rm=T),
                                                          lam.fish.mn = mean(lam.fish,na.rm=T),
                                                          lam.org.no.fish.mn = mean(lam.org.no.fish,na.rm=T),
                                                          lam.org.fish.mn = mean(lam.org.fish,na.rm=T),
                                                          lam.no.fish.med = median(lam.no.fish,na.rm=T),
                                                          lam.fish.med = median(lam.fish,na.rm=T),
                                                          lam.org.no.fish.med = median(lam.org.no.fish,na.rm=T),
                                                          lam.org.fish.med = median(lam.org.fish,na.rm=T)) |> data.frame()

res.lambda.final.6 <- res.lambda.fin |> collapse::fsubset(Species %in% six.species)
# Sort the data into a nice order...
res.lambda.fin <- res.lambda.fin |> collapse::roworder(Species,Area.broad) |>
                                    collapse::fmutate(Stock.no.species = forcats::fct_inorder(factor(Stock.no.species, ordered=TRUE)))
res.lambda.final.6 <- res.lambda.final.6 |> collapse::roworder(Species,Area.broad) |>
                                            collapse::fmutate(Stock.no.species = forcats::fct_inorder(factor(Stock.no.species, ordered=TRUE)))
dub.time <- dub.time |> collapse::roworder(LME) |>
                        collapse::fmutate(Stock.no.species = forcats::fct_inorder(factor(Stock.no.species, ordered=TRUE)))

dub.time.summary <- dub.time.summary |> collapse::roworder(LME,Order,Species,Area.broad) |>
                                        collapse::fmutate(Stock.short = forcats::fct_inorder(factor(Stock.short, ordered=TRUE)))

dub.time.6 <- dub.time.6 |> collapse::roworder(LME) |>
                             collapse::fmutate(Stock.no.species = forcats::fct_inorder(factor(Stock.no.species, ordered=TRUE)))
pop.dam <- pop.dam |> collapse::roworder(Species,LME) |>
                       collapse::fmutate(Stock = forcats::fct_inorder(factor(Stock, ordered=TRUE)))
pop.dam.6 <- pop.dam.6 |> collapse::roworder(LME,Area.broad) |>
                       collapse::fmutate(Stock.no.species = forcats::fct_inorder(factor(Stock.no.species, ordered=TRUE)))

# res.lambda.final.6 <- res.lambda.final.6 |> collapse::roworder(LME,Area.broad) |>
#                                              collapse::fmutate(Stock.no.species = forcats::fct_inorder(factor(Stock.no.species, ordered=TRUE)))
            
################### Figures in main text################### Figures in main text################### Figures in main text################### 

#hmm <- merge(tst,res.lambda.final.6,by="Stock")
plot(res.lambda.fin$lam.fish.med ~ res.lambda.fin$lam.fish.mn)
# So this is lambda with fishing included
lambda.plt <- ggplot(res.lambda.final.6) + geom_boxplot(aes(y=lam.no.fish,x=Stock.no.species))  + 
                                           geom_point(aes(y=lam.no.fish.mn,x=Stock.no.species),color='blue',shape=8,fill='blue') +
                                           xlab("") + scale_y_log10("lambda",breaks = c(0.1,0.4,0.6,0.8,1,1.25,1.75,3,5,10),limits=c(0.4,10)) + 
                                           geom_hline(yintercept = 1,linetype='dashed') +
                                           facet_wrap(~G.Species,scales='free')+
                                           theme(axis.text.x = element_text(angle =45,hjust=1),legend.position = 'none',
                                                 plot.margin = margin(0,0.5,0,0.5, "cm"),axis.title.y = element_text(margin = margin(r = 30)))

save_plot(paste0(loc,"/Figures/tuned/No_age_correction/lambda_no_fishing_6_",what.2.tune,".png"),lambda.plt,base_width = 12,base_height = 10)

# With fishing
lambda.plt.fish <- ggplot(res.lambda.final.6) + geom_boxplot(aes(y=lam.fish,x=Stock.no.species))  + 
                                           geom_point(aes(y=lam.fish.mn,x=Stock.no.species),color='blue',shape=8,fill='blue') +
                                           xlab("") + scale_y_log10("lambda",breaks = c(0.4,0.6,0.8,1,1.25,1.75,3,5,10),limits=c(0.4,10)) + 
                                           geom_hline(yintercept = 1,linetype='dashed') +
                                           facet_wrap(~G.Species,scales='free')+
                                           theme(axis.text.x = element_text(angle =45,hjust=1),legend.position = 'none',
                                                 plot.margin = margin(0,0.5,0,0.5, "cm"),axis.title.y = element_text(margin = margin(r = 30)))


save_plot(paste0(loc,"/Figures/tuned/No_age_correction/lambda_with_fishing_6_",what.2.tune,".png"),lambda.plt.fish,base_width = 12,base_height = 10)


# Doubling Times

dub.heatmap.cod <- ggplot(dub.time.6 |> collapse::fsubset(G.Species == "G. morhua"), aes(x=year, y=Stock.no.species, fill= prop)) + xlab("") + ylab("")+                                     facet_wrap(~G.Species,nrow=3,scales='free_y',strip.position = "right") + 
                            geom_tile() + scale_fill_viridis(name = "Proportion",discrete=FALSE) + scale_x_continuous(labels=NULL) +
                            theme(legend.position = 'top',text = element_text(size=12),plot.margin = margin(0,0.5,0,0, "cm"),
                                  legend.key.width = unit(3,'cm'))

dub.heatmap.herring<- ggplot(dub.time.6 |> collapse::fsubset(G.Species == "C. harengus"), aes(x=year, y=Stock.no.species, fill= prop)) + 
                              xlab("") + ylab("")+                                    
                              facet_wrap(~G.Species,nrow=3,scales='free_y',strip.position = "right") + scale_x_continuous(labels=NULL) +
                              geom_tile() + scale_fill_viridis(name = "Proportion",discrete=FALSE) + 
                              theme(legend.position = 'none',text = element_text(size=12),plot.margin = margin(0,0.5,0,0.4, "cm"))

dub.heatmap.haddock<- ggplot(dub.time.6 |> collapse::fsubset(G.Species == "M. aeglefinus"), aes(x=year, y=Stock.no.species, fill= prop)) + 
                              xlab("") + ylab("")+                                    
                              facet_wrap(~G.Species,nrow=3,scales='free_y',strip.position = "right") + scale_x_continuous(labels=NULL) +
                              geom_tile() + scale_fill_viridis(name = "Proportion",discrete=FALSE) + 
                              theme(legend.position = 'none',text = element_text(size=12),plot.margin = margin(0,0.5,0,0.125, "cm"))

dub.heatmap.virens<- ggplot(dub.time.6 |> collapse::fsubset(G.Species == "P. virens"), aes(x=year, y=Stock.no.species, fill= prop)) + 
                              xlab("") + ylab("")+                                    
                              facet_wrap(~G.Species,nrow=3,scales='free_y',strip.position = "right") + scale_x_continuous(labels=NULL) +
                              geom_tile() + scale_fill_viridis(name = "Proportion",discrete=FALSE) + 
                              theme(legend.position = 'none',text = element_text(size=12),plot.margin = margin(0,0.5,0,1.4, "cm"))

dub.heatmap.solea<- ggplot(dub.time.6 |> collapse::fsubset(G.Species == "S. solea"), aes(x=year, y=Stock.no.species, fill= prop)) + 
                              xlab("") + ylab("")+                                    
                              facet_wrap(~G.Species,nrow=3,scales='free_y',strip.position = "right") + scale_x_continuous(labels=NULL) +
                              geom_tile() + scale_fill_viridis(name = "Proportion",discrete=FALSE) + 
                              theme(legend.position = 'none',text = element_text(size=12),plot.margin = margin(0,0.5,0,0.4, "cm"))

dub.heatmap.platessa<- ggplot(dub.time.6 |> collapse::fsubset(G.Species == "P. platessa"), aes(x=year, y=Stock.no.species, fill= prop)) + 
                              xlab("") + ylab("")+                                    
                              facet_wrap(~G.Species,nrow=3,scales='free_y',strip.position = "right") + scale_x_continuous() +
                              geom_tile() + scale_fill_viridis(name = "Proportion",discrete=FALSE) + 
                              theme(legend.position = 'none',text = element_text(size=12),plot.margin = margin(0,0.5,0,0.68, "cm"))



dub.heatmap.sp6 <- cowplot::plot_grid(dub.heatmap.cod,dub.heatmap.herring,dub.heatmap.haddock,
                                 dub.heatmap.virens, dub.heatmap.solea,dub.heatmap.platessa,nrow = 6,rel_heights = c(14,9,8,5,5,4))
dub.heatmap.sp6

save_plot(paste0(loc,"/Figures/tuned/No_age_correction/Doubling_time_heatmap_by_sp6_",what.2.tune,".png"),dub.heatmap.sp6,base_width = 20,base_height = 17)



# Generation length

gen.boxplt <- ggplot(pop.dam.6) +
                            geom_boxplot(aes(y=gen.len.opt,x=Stock.no.species))  + 
                            xlab("") + scale_y_continuous("Generation Length (years)",limits=c(0,13),breaks= seq(0,20,by=2)) +
                            facet_wrap(~G.Species,scales='free_x')+
                            theme(axis.text.x = element_text(angle =45,hjust=1),legend.position = 'none',plot.margin = margin(0,0.5,0,0.5, "cm"),
                                  axis.title.y = element_text(margin = margin(r = 30)))

save_plot(paste0(loc,"/Figures/tuned/No_age_correction/GL_boxplot_no_fish_6_species_",what.2.tune,".png"),gen.boxplt,base_width = 12,base_height = 10)

# Lifetime reproductive success (no fishing)


r0.boxplt <- ggplot(pop.dam.6) +
                            geom_boxplot(aes(y=R0.opt,x=Stock.no.species))  + 
                            xlab("") + scale_y_log10(name = "Lifetime Reproductive Output")+
                            geom_hline(yintercept = 1,linetype='dashed',color='blue')+
                            facet_wrap(~G.Species,scales = 'free')+
                            theme(axis.text.x = element_text(angle =45,hjust=1),legend.position = 'none',plot.margin = margin(0,0.5,0,0.5, "cm"),
                                  axis.title.y = element_text(margin = margin(r = 30)))

save_plot(paste0(loc,"/Figures/tuned/No_age_correction/R0_boxplot_no_fish_6_species_",what.2.tune,".png"),r0.boxplt,base_width = 12,base_height = 10)




################### Supplemental Figures################### Supplemental Figures################### Supplemental Figures################### Supplemental 

# Reorder the doubling time, either by Species and LME, or the other way around

dub.time.summary$Order.short <- "Gadi"
dub.time.summary$Order.short[dub.time.summary$Order == "Pleuronectiformes"] <- "Plero"
dub.time.summary$Order.short[dub.time.summary$Order == "Clupeiformes"] <- "Clupei"
dub.time.summary$Order.short[dub.time.summary$Order == "Scorpaeniformes "] <- "Scor"
dub.time.summary$Order.short[dub.time.summary$Order == "Scombriformes"] <- "Scomb"
dub.time.summary$Order.short[dub.time.summary$Order == "Perciformes"] <- "Perci"

dub.time.summary <- dub.time.summary |>
                            collapse::roworder(G.Species,LME,Area.broad) |>
                            collapse::fmutate(Stock.short = forcats::fct_inorder(factor(Stock.short, ordered=TRUE)))
              
dub.heatmap.gad <- ggplot(dub.time.summary |> collapse::fsubset(Order == "Gadiformes"), aes(x=year, y=Stock.short, fill= prop)) + 
                            xlab("") + ylab("")+                                    
                            facet_wrap(~Order.short,nrow=3,scales='free_y',strip.position = "right") + scale_x_continuous(labels=NULL) +
                            geom_tile() + scale_fill_viridis(name = "Proportion",discrete=FALSE) + 
                            theme(legend.position = 'top',text = element_text(size=12),plot.margin = margin(0,0.5,0,0.45, "cm"),
                                  legend.key.width = unit(3,'cm'))

dub.heatmap.pl <- ggplot(dub.time.summary |> collapse::fsubset(Order == "Pleuronectiformes"), aes(x=year, y=Stock.short, fill= prop)) + 
                            xlab("") + ylab("")+                                    
                            facet_wrap(~Order.short,nrow=3,scales='free_y',strip.position = "right") + scale_x_continuous(labels=NULL) +
                            geom_tile() + scale_fill_viridis(name = "Proportion",discrete=FALSE) + 
                            theme(legend.position = 'none',text = element_text(size=12),plot.margin = margin(0,0.5,0,0, "cm"))

dub.heatmap.cl <- ggplot(dub.time.summary |> collapse::fsubset(Order == "Clupeiformes"), aes(x=year, y=Stock.short, fill= prop)) + 
                            xlab("") + ylab("")+
                            facet_wrap(~Order.short,nrow=3,scales='free_y',strip.position = "right") + scale_x_continuous(labels=NULL) +
                            geom_tile() + scale_fill_viridis(name = "Proportion",discrete=FALSE) + 
                            theme(legend.position = 'none',text = element_text(size=12),plot.margin = margin(0,0.5,0,1.35, "cm"),
                                  legend.key.width = unit(3,'cm'))

dub.heatmap.per <- ggplot(dub.time.summary |> collapse::fsubset(Order == "Perciformes"), aes(x=year, y=Stock.short, fill= prop)) + 
                            xlab("") + ylab("")+
                            facet_wrap(~Order.short,nrow=3,scales='free_y',strip.position = "right") + scale_x_continuous(labels=NULL) +
                            geom_tile() + scale_fill_viridis(name = "Proportion",discrete=FALSE) + 
                            theme(legend.position = 'none',text = element_text(size=12),plot.margin = margin(0,0.5,0,2, "cm"),
                                  legend.key.width = unit(3,'cm'))

dub.heatmap.scom <- ggplot(dub.time.summary |> collapse::fsubset(Order == "Scombriformes"), aes(x=year, y=Stock.short, fill= prop)) + 
                            xlab("") + ylab("")+
                            facet_wrap(~Order.short,nrow=3,scales='free_y',strip.position = "right") + scale_x_continuous(labels=NULL) +
                            geom_tile() + scale_fill_viridis(name = "Proportion",discrete=FALSE) + 
                            theme(legend.position = 'none',text = element_text(size=12),plot.margin = margin(0,0.5,0,2.1, "cm"),
                                  legend.key.width = unit(3,'cm'))

dub.heatmap.scorp <- ggplot(dub.time.summary |> collapse::fsubset(Order %in% "Scorpaeniformes "), aes(x=year, y=Stock.short, fill= prop)) + 
                            xlab("") + ylab("")+
                            facet_wrap(~Order.short,nrow=3,scales='free_y',strip.position = "right") + 
                            geom_tile() + scale_fill_viridis(name = "Proportion",discrete=FALSE) + 
                            theme(legend.position = 'none',text = element_text(size=12),plot.margin = margin(0,0.5,0,0.5, "cm"),
                                  legend.key.width = unit(3,'cm'))



dub.heatmap <- cowplot::plot_grid(dub.heatmap.gad,dub.heatmap.pl,dub.heatmap.cl,dub.heatmap.per,dub.heatmap.scom,dub.heatmap.scorp,
                                  nrow = 6,rel_heights = c(39,20,11,4,3,3))
dub.heatmap

save_plot(paste0(loc,"/Figures/tuned/No_age_correction/Doubling_time_heatmap_by_order_",what.2.tune,".png"),dub.heatmap,base_width = 20,base_height = 20)

# Time series of lambdas....
col.try <- rep(rep(c("black","blue","orange",'firebrick2','lightgreen'),3),20)
#col.try <- rep(c(rep("black",3),rep("blue",3),rep('orange',3),rep('firebrick2',3),rep('lightgreen',3)),20)
pty <- rep(c(rep(21,5),rep(22,5),rep(23,5)),20)
#pty <- rep(rep(c(21:23),5),20)

lambda.ts.plt <- ggplot(res.lambda.final.6,aes(y=lam.fish,x=year,group=Stock.short,color=Stock.short,shape = Stock.short,fill = Stock.short)) +
                            geom_point(size=4) +
                            geom_smooth(method='gam',formula = y ~ s(x, bs = "cs", fx = TRUE, k = 5),se=F) + 
                            #scale_y_log10(name = "lambda") +
                            facet_wrap(~G.Species,scales='free_y') +
                            scale_color_manual(name = "Stock",values = col.try) + scale_shape_manual(name = "Stock",values = pty) +
                            scale_fill_manual(name = "Stock",values = col.try)+
                            guides(colour = guide_legend(ncol = 1))+
                            theme(axis.text.x = element_text(angle =45,hjust=1),legend.key.width = unit(5,'cm'))
#lambda.ts.plt
save_plot(paste0(loc,"/Figures/tuned/No_age_correction/lambda_timeseries_6_",what.2.tune,".png"),lambda.ts.plt,base_width = 12,base_height = 10)


lambda.dec.plt <- ggplot(res.lambda.final.6,aes(y=med.lam,x=as.factor(decade))) +
                            geom_boxplot() + scale_y_log10()+
                            xlab("Decade") + ylab("Lambda") + 
                            geom_point(aes(x=as.factor(decade),y=lm.spec.mn),color='blue',shape=8,fill='blue')+
                            #scale_x_continuous(breaks=seq(1940,2020,by=10))+
                            geom_hline(yintercept = 1,linetype='dashed') +
                            facet_wrap(~G.Species,scales='free_y') 
save_plot(paste0(loc,"/Figures/tuned/No_age_correction/lambda_by_decade_6_",what.2.tune,".png"),lambda.dec.plt,base_width = 12,base_height = 12)





gen.heatmap.ne <- ggplot(pop.dam |> collapse::fsubset(LME == "NE Atlantic"), aes(x=cohort, y=Stock.short, fill= gen.len.opt)) + 
                                              xlab("") + ylab("")+  
                                              facet_wrap(~LME,nrow=3,scales='free_y',strip.position = "right") + 
                                              geom_tile() + scale_fill_viridis(name = "Generation length (years)",discrete=FALSE) + 
                                              theme(legend.position = 'none',text = element_text(size=12),plot.margin = margin(0,0.5,0,0.9, "cm"))

gen.heatmap.nw <- ggplot(pop.dam |> collapse::fsubset(LME == "NW Atlantic"), aes(x=cohort, y=Stock.short, fill= gen.len.opt)) + xlab("") + ylab("")+                                    facet_wrap(~LME,nrow=3,scales='free_y',strip.position = "right") + scale_x_continuous(labels=NULL) +
                            geom_tile() + scale_fill_viridis(name = "Generation length (years)",discrete=FALSE) + 
                            theme(legend.position = 'none',text = element_text(size=12),plot.margin = margin(0,0.5,0,1.22, "cm"))

gen.heatmap.pac <- ggplot(pop.dam |> collapse::fsubset(LME == "Pacific (Alaska)"), aes(x=cohort, y=Stock.short, fill= gen.len.opt)) + xlab("") + ylab("")+
                            facet_wrap(~LME,nrow=3,scales='free_y',strip.position = "right") + scale_x_continuous(labels=NULL) +
                            geom_tile() + scale_fill_viridis(name = "Generation length (years)",discrete=FALSE) + 
                            theme(legend.position = 'top',text = element_text(size=12),plot.margin = margin(0,0.5,0,0, "cm"),
                                  legend.key.width = unit(3,'cm'))

gen.heatmap <- cowplot::plot_grid(gen.heatmap.pac,gen.heatmap.nw,gen.heatmap.ne,nrow = 3,rel_heights = c(3,4,10))
gen.heatmap

save_plot(paste0(loc,"/Figures/tuned/No_age_correction/gen_heatmap_",what.2.tune,".png"),gen.heatmap,base_width = 20,base_height = 17)

r0.heatmap.ne <- ggplot(pop.dam |> collapse::fsubset(LME == "NE Atlantic"), aes(x=cohort, y=Stock.short, fill= R0.opt)) + 
                                    xlab("") + ylab("")+
                                    facet_wrap(~LME,nrow=3,scales='free_y',strip.position = "right") + 
                                    geom_tile() + 
                                     scale_fill_viridis(name = "Lifetime reproductive success", breaks = c(0.4,1,2,4,10,20,40,100,200,400),
                                                        discrete=FALSE,trans='log') + 
                                    theme(legend.position = 'none',text = element_text(size=12),plot.margin = margin(0,0.5,0,0.9, "cm"))

r0.heatmap.nw <- ggplot(pop.dam |> collapse::fsubset(LME == "NW Atlantic"), aes(x=cohort, y=Stock.short, fill= R0.opt)) + 
                                    xlab("") + ylab("")+
                                    facet_wrap(~LME,nrow=3,scales='free_y',strip.position = "right") + scale_x_continuous(labels=NULL) +
                                    geom_tile() + 
                                     scale_fill_viridis(name = "Lifetime reproductive success", breaks = c(0.4,1,2,4,10,20,40,100,200,400),
                                                        discrete=FALSE,trans='log') + 
                                    theme(legend.position = 'none',text = element_text(size=12),plot.margin = margin(0,0.5,0,1.22, "cm"))

r0.heatmap.pac <- ggplot(pop.dam |> collapse::fsubset(LME == "Pacific (Alaska)"), aes(x=cohort, y=Stock.short, fill= R0.opt)) + 
                                     xlab("") + ylab("")+
                                     facet_wrap(~LME,nrow=3,scales='free_y',strip.position = "right") + scale_x_continuous(labels=NULL) +
                                     geom_tile() + 
                                     scale_fill_viridis(name = "Lifetime reproductive success", breaks = c(0.4,1,2,4,10,20,40,100,200,400),
                                                        discrete=FALSE,trans='log') + 
                                     theme(legend.position = 'top',text = element_text(size=12),plot.margin = margin(0,0.5,0,0, "cm"),
                                           legend.key.width = unit(3,'cm'))

r0.heatmap <- cowplot::plot_grid(r0.heatmap.pac,r0.heatmap.nw,r0.heatmap.ne,nrow = 3,rel_heights = c(3,4,10))
r0.heatmap

save_plot(paste0(loc,"/Figures/tuned/No_age_correction/r0_heatmap_",what.2.tune,".png"),r0.heatmap,base_width = 20,base_height = 17)

# FIX: A density dependence figure, this isn't perfect as the lambda's aren't quiet lined up right because of recruitment offset
# That said, recruitment in these cases also integrates all processes that happens from birth-recruitment
# So maybe it is kinda reasonable?
#

# First need to get the abundance and lambdas with no fishing into one object.
ft.tmp <- for.tunes |> collapse::fselect(year,Stock,vpa.abund,est.abund)
dd.dat <- left_join(res.lambda.fin,ft.tmp,by=c('year','Stock'))
# Now I need to get a relative abundance for each stock...
dd.dat <- dd.dat |> collapse::fgroup_by(Stock) |> collapse::fmutate(max.abund = max(est.abund,na.rm=T))
dd.dat <- data.frame(dd.dat)
dd.dat$prop.abund <- dd.dat$est.abund/dd.dat$max.abund
dd.dat.six <- dd.dat |>collapse::fsubset(Species %in% six.species)

ggplot(dd.dat) + geom_point(aes(x=prop.abund,y=lam.no.fish-1)) + xlab("Proportion of Maximum Abundance") + ylab("r (no fishing)")

# Density dependence by Species
ggplot(dd.dat,aes(x=prop.abund,y=lam.no.fish,color=Species,group=Species)) + geom_point() + 
                                                   geom_smooth(method="gam") + 
                                                   geom_hline(yintercept = 1,linewidth=2,linetype='dashed',color='blue') +
                                                   scale_x_continuous(name = "Proportion of Maximum Abundance", breaks = seq(0,1,by=0.1))+
                                                   scale_y_log10(name = "lambda (no fishing)", breaks = c(0.5,0.75,1,1.5,2.5,3.5,5,7.5,10,12.5)) #+
                                                   #scale_color_manual(values = colrs)
# Density dependence by stock
ggplot(dd.dat,aes(x=prop.abund,y=lam.no.fish,color=Stock.short,group=Stock.short)) + geom_point() + 
                                                   geom_smooth(method="lm",se = F) + 
                                                   geom_hline(yintercept = 1,linewidth=2,linetype='dashed',color='blue') +
                                                   scale_x_continuous(name = "Proportion of Maximum Abundance", breaks = seq(0,1,by=0.1))+
                                                   scale_y_log10(name = "lambda (no fishing)", limits=c(0.4,2),
                                                                 breaks = seq(0.4,2,by=0.1)) +
                                                   theme(legend.position = 'none')



dd.dat.no.bigs <- dd.dat |> collapse::fsubset(lam.no.fish < 2)

ggplot(dd.dat.no.bigs,aes(x=prop.abund,y=lam.no.fish)) + geom_point() + 
                                                    geom_smooth(method="gam") + 
                                                   geom_hline(yintercept = 1,linewidth=2,linetype='dashed',color='blue') +
                                                   scale_x_continuous(name = "Proportion of Maximum Abundance", breaks = seq(0,1,by=0.1))+
                                                   scale_y_continuous(name = "lambda (no fishing)")

ggplot(dd.dat.no.bigs,aes(x=prop.abund,y=lam.no.fish,group=Stock.short,color=Stock.short)) + geom_point() + 
                                                    geom_smooth(method="lm",se=F) + 
                                                   geom_hline(yintercept = 1,linewidth=2,linetype='dashed',color='blue') +
                                                   scale_x_continuous(name = "Proportion of Maximum Abundance", breaks = seq(0,2,by=0.1))+
                                                   scale_y_log10(name = "lambda (no fishing)")


# how about our big 6
colrs <- c("blue","black","firebrick2","orange",'grey50','grey90')
ggplot(dd.dat.six,aes(x=prop.abund,y=lam.no.fish,color=Species,group=Species)) + geom_point() + 
                                                    geom_smooth(method="gam") + 
                                                   geom_hline(yintercept = 1,linewidth=2,linetype='dashed',color='blue') +
                                                   scale_x_continuous(name = "Proportion of Maximum Abundance", breaks = seq(0,1,by=0.1))+
                                                   scale_y_log10(name = "lambda (no fishing)", breaks = c(0.5,0.75,1,1.5,2.5,3.5,5,7.5,10,12.5)) +
                                                   scale_color_manual(values = colrs)

dd.dat.six.no.bigs <- dd.dat.six |> collapse::fsubset(lam.no.fish < 2)

ggplot(dd.dat.six.no.bigs,aes(x=prop.abund,y=lam.no.fish-1,color=Species,group=Species)) + geom_point() + 
                                                    geom_smooth(method="gam") + 
                                                   geom_hline(yintercept = 0,linewidth=2,linetype='dashed',color='blue') +
                                                   scale_x_continuous(name = "Proportion of Maximum Abundance", breaks = seq(0,1,by=0.1))+
                                                   scale_y_continuous(name = "r (no fishing)", breaks = seq(-1,1,by=0.2)) +
                                                   scale_color_manual(values = colrs)


just.bigs <- dd.dat  |> collapse::fsubset(lam.no.fish > 2) 
sum(table(just.bigs$Stock.short)) # 48 of 68 are Haddock or cod. 13 of remaining 20 are small low trophic species

dd.dat$lam.ratio <- dd.dat$lam.org.no.fish/dd.dat$lam.no.fish
dd.dat$lam.ratio.z <- dd.dat$lam.org.fish/dd.dat$lam.fish
# So the original lambda tended to be somewhere between 7 and 14% higher, depending on me(di)an choice.
# Could be way off in some years for a few species (Haddock, Cod, Sand lance, horse makerel, pilchard(sardine)... interesting... )
summary(dd.dat$lam.ratio)
summary(dd.dat$lam.ratio.z)
ggplot(dd.dat,aes(y=lam.ratio,x=Species)) + geom_violin() + scale_y_log10() + geom_hline(yintercept =1) + theme_few(base_size=9)
ggplot(dd.dat,aes(y=lam.ratio.z,x=Species)) + geom_violin() + scale_y_log10() + geom_hline(yintercept =1) + theme_few(base_size=9)
# Other figures....

# windows(11,11)
# col.try <- rep(rep(c("black","blue","orange",'firebrick2','lightgreen'),3),20)
# pty <- rep(c(rep(21,5),rep(22,5),rep(23,5)),20)

# 
# r0.ts.plt <- ggplot(pop.dam.6,aes(y=R0.opt,x=cohort,group=Stock.short,color=Stock.short,shape = Stock.short,fill = Stock.short)) + 
#                             geom_line(size=2)  + geom_point(size=4) +
#                             scale_y_log10(name = "Lifetime Reproductive Output") +
#                             facet_wrap(~G.Species) +
#                             scale_color_manual(name = "Stock",values = col.try) + scale_shape_manual(name = "Stock",values = pty) +
#                             scale_fill_manual(name = "Stock",values = col.try)+
#                             guides(colour = guide_legend(ncol = 1))+
#                             theme(axis.text.x = element_text(angle =45,hjust=1),legend.key.width = unit(5,'cm')) 
# r0.ts.plt
# 
# save_plot("D:/Github/ICM/Figures/tuned/R0_timeseries_6.png",r0.ts.plt,base_width = 30,base_height = 12)
# 
# r0.boxplt <- ggplot(pop.dam) + geom_boxplot(aes(y=R0.opt,x=Stock.no.species))  + 
#                             scale_y_log10(name = "Lifetime Reproductive Output")+#, breaks = c(0.001,0.01,0.1,1,5,10,50,100),minor_breaks = NULL) + 
#                             facet_wrap(~G.Species,scales = 'free')+
#                             theme(axis.text.x = element_text(angle =45,hjust=1),legend.position = 'none')
# r0.boxplt



# 
# windows(11,11)
# ggplot(pop.dam) + geom_boxplot(aes(y=gen.len.opt,x=Species)) + facet_wrap(~LME,scales='free_x') +
#                   ylab("Generation Length (years)") + theme(axis.text.x = element_text(angle =45,hjust=1))
# 
# windows(11,11)
# col.try <- rep(rep(c("black","blue","orange",'firebrick2','lightgreen'),3),20)
# lty <- rep(c(rep(1,5),rep(2,5),rep(4,5)),20)
# 
# gen.ts.plt <- ggplot(pop.dam.6,aes(y=gen.len.opt,x=cohort,group=Stock.short,color=Stock.short,linetype = Stock.short)) + 
#                             geom_line(size=2)  + 
#                             scale_y_log10(name = "Generation Length") +
#                             facet_wrap(~G.Species) +
#                             scale_color_manual(name = "Stock",values = col.try) + scale_linetype_manual(name = "Stock",values = lty) +
#                             guides(colour = guide_legend(ncol = 1))+
#                             theme(axis.text.x = element_text(angle =45,hjust=1),legend.key.width = unit(5,'cm')) 
# gen.ts.plt
# save_plot("D:/Github/ICM/Figures/tuned/Gen_time_series_6.png",gen.ts.plt,base_width = 20,base_height = 12)

# 
# ggplot(for.tunes) + geom_jitter(aes(y=lambda,x=Species,group=Stock.short,color=Stock.short)) + 
#                     scale_y_continuous(name = 'rate of growth (lambda)',breaks = c(-1,-0.5,0,0.5,1:10)) +
#                             theme(axis.text.x = element_text(angle =45,hjust=1))
# 
# ggplot(for.tunes) + geom_jitter(aes(y=lambda.vpa.init,x=Species)) + scale_y_continuous(name = 'rate of growth (lambda)',breaks = c(-1,-0.5,0,0.5,1:10),limits = c(-1,3))
# 
# unique(for.tunes$Species)
# windows(11,11)
# 
# ggplot(for.tunes) + geom_density(aes(lambda,group=Species,color=Species,fill=Species),alpha = 0.2) + scale_x_continuous(breaks = c(0,0.5,1,2,5,10))
# 
# 
# #options(scipen=999)
# r0.plt <- ggplot(pop.dam) + geom_boxplot(aes(y=R0.opt,x=Area))  + 
#                             scale_y_log10(name = "Lifetime Reproductive Output")+#, breaks = c(0.001,0.01,0.05,0.1,0.5,1,5,10,50,100),minor_breaks = NULL) + 
#                             facet_wrap(~Species,scales = 'free')+
#                             theme(axis.text.x = element_text(angle =45,hjust=1))
# save_plot("D:/Github/ICM/Figures/tuned/R0_ignoring_fishing.png",r0.plt,base_width = 8,base_height = 8)
# 
# 
# 
# vickis.cols <- sort(rep(c( "#172582",  "#F8DC91", "#FBB891", "#FB6A01", "#B80000"),3))
# linetypes <- rep(c(1,2,4),5)
# 
# windows(11,11)
# cod.r0.ts.plt <- ggplot(pop.dam |> collapse::fsubset(Species == 'morhua')) + geom_line(aes(y=R0.opt,x=cohort,group=Area,color=Area,linetype=Area),size=1.5)  + 
#                             scale_y_log10(name = "Lifetime Reproductive Output", breaks = c(0.001,0.01,0.1,1,5,10,50,100),minor_breaks = NULL) + 
#                             scale_color_manual(values = vickis.cols) +
#                             scale_linetype_manual(values = linetypes) +
#                             theme(legend.key.width  = unit(2, "cm"))
# cod.r0.ts.plt
# #save_plot("D:/Github/ICM/Figures/tuned/R0_timeseries_ignoring_fishing.png",r0.plt,base_width = 8,base_height = 8)
# 
# 
# windows(11,11)
# ggplot(pop.dam |> collapse::fsubset(Species =="morhua")) + geom_boxplot(aes(y=R0.opt,x=Area))  + 
#                                                         scale_y_log10(name = "Lifetime Reproductive Output",breaks = c(0.001,0.01,0.1,1,5,10,50,100),minor_breaks = NULL) +
#                                                         theme(axis.text.x = element_text(angle =45,hjust=1))
# 
# # Missing catch questions
# # first did we do much to the Fecundity term to get here
# quantile(for.tunes$mean.fec/for.tunes$mean.vpa.fec,probs=seq(0.01,1,0.01),na.rm=T)
# 
# quantile((for.tunes$removals-for.tunes$removals.init)/for.tunes$removals.init,probs=seq(0.01,1,0.01),na.rm=T)
# quantile((for.tunes$mean.nm-for.tunes$mean.vpa.nm)/for.tunes$mean.vpa.nm,probs=seq(0.01,1,0.01),na.rm=T)
# 
# for.tunes$excess.catch <- for.tunes$removals-for.tunes$removals.init
# for.tunes$per.excess.catch <- 100*((for.tunes$removals-for.tunes$removals.init)/for.tunes$removals.init)
# 
# windows(11,11)
# bycatch.plt <- ggplot(for.tunes) + geom_boxplot(aes(y=per.excess.catch,x=Species)) + 
#                                    ylab("Adjustment to catch (%)") +
#                                    theme(axis.text.x = element_text(angle=45,hjust = 1))
#                                    
# save_plot("D:/Github/ICM/Figures/tuned/Percentage_change_to_bycatch_by_species.png",bycatch.plt,base_width = 8,base_height = 8)
#                                    
# bycatch.plt.cod <- ggplot(for.tunes |> collapse::fsubset(Species == 'morhua')) + geom_boxplot(aes(y=per.excess.catch,x=Area)) + 
#                                                                               ylab("Adjustment to catch (%)") +
#                                                                               theme(axis.text.x = element_text(angle=45,hjust = 1))
#                                                                               
# save_plot("D:/Github/ICM/Figures/tuned/Percentage_change_to_bycatch_by_cod_stock.png",bycatch.plt.cod,base_width = 8,base_height = 8)
# 
# # bycatch.plt <- ggplot(for.tunes) + geom_boxplot(aes(y=per.excess.catch,x=Area)) + facet_wrap(~Species,scales = 'free_x')
# #                                    ylab("Adjustment to catch (%)") +
# #                                    theme(axis.text.x = element_text(angle=45,hjust = 1))
# # bycatch.plt                                   
#                        

# Doubling time for the rest of the stocks...

# dub.heatmap.no.6 <- ggplot(dub.time.summary |> collapse::fsubset(!Species %in% six.species), aes(x=year, y=Stock.short, fill= prop)) + 
#                               xlab("") + ylab("")+                                    
#                               #facet_wrap(~G.Species,nrow=3,scales='free_y',strip.position = "right") + 
#                               scale_x_continuous() +
#                               geom_tile() + scale_fill_viridis(name = "Proportion",discrete=FALSE) + 
#                               theme(legend.position = 'none',text = element_text(size=12),plot.margin = margin(0,0.5,0,0.68, "cm"))
```