# INTRODUCTION  {#intro}

Marine fishes were once believed to be extremely resilient to the effects of fishing. However, high profile collapses of large fisheries and a subsequent lack of rebuilding (ref, ref) have fundamentally challenged this perception. Much of fisheries science throughout the second half of the 20th century was  built around the concept of maximum sustainable yield (MSY), from the outset this concept was controversial and even had an epitaph written almost half a century ago [@larkinEpitaphConceptMaximum1977; @finleyAllFishSea2019]. However, the ecological concepts underpinning MSY theory and their use has  proven remarkable resilient themselves, in part, because 1) the population dynamics are relatively simple and intuitive, 2) they provide a means of developing tractable mechanistic models, 3) fisheries science built robust methodologies to collect the necessary data for these models, and 4) the management frameworks had been implemented around these models and they provide a very useful tactical decision making platform. As such, the concerns around the sustainability of *modern* fisheries science techniques shows little sign of being resolved [@wormRebuildingGlobalFisheries2009; Maybe cite an EAFM and MPA paper?].

The view that marine populations are highly resilient likely originates from the views of some of the first fisheries scientists who suggested that marine fisheries were effectively inexhaustible [e.g., mcintoshFisheriesInterNationalCouncil1919a; @mcintoshFisheriesInternationalCouncil1919]. These ideas were subsequently married to the theoretical results from some of the earliest population dynamic models [e.g., @verhulstNoticeLoiQue1838] and lead to the development of *modern* fisheries science and MSY theory [@rickerStockRecruitment1954; @schaeferAspectsDynamicsPopulations1954; @bevertonDynamicsExploitedFish1957; ]. Fundamentally, the belief was that the annual reproductive output and/or juvenile survival rates would increase as abundance declines, otherwise fisheries would collapse (REF), while the old paradigm that fisheries were inexhaustible was no longer supported, the new paradigm indicated that increased harvesting activity would result in the increased *productivity* of a population. The subsequent models developed assumed that marine fishes would retain a latent capacity for increase, even if managed in such a way that fisheries removals balance population growth (under equilibrium conditions). This means that populations always have the ability to increase in size, and their lifetime reproductive rates in the absence of fishing would be expected to be greater than one (ref, ref). At the time many of these fisheries scientists identified the challenges and limitations of their modelling frameworks, including concerns about how applicable these concepts were for species with different life history characteristics, e.g., how different would the fisheries impact be on long lived species with low fecundity and short lived species with high fecundity (CITE SOMETHING).

Life history characteristics are now considered indicative of a species’ compensatory capacity and are increasingly used within data-limited assessment approaches to provide management advice (ref).  Theory suggests that small fishes, characterized by numerous offspring, rapid growth, early maturity and short lifespans, should have greater compensatory capacity, resilience to environmental variability and consequently, be better able to withstand fishing pressure (Kindsvader et al. 2016. Ref, ref). Life histories characterized by longer lifespans and later maturity, or those with lower per-capita reproductive output are considered less resilient. Furthermore, closely related species are anticipated to be more similar than distantly related species owing to a shared evolutionary history (Thorson fishlife). This has led to the general impression that forage fishes or populations at lower trophic levels are better able to take advantage of favorable environmental conditions and grow more quickly, particularly from low abundance (ref, ref). This resilience should manifest as a high latent capacity for population growth in the absence of fishing, as well as substantial variability in realized population growth rates among years. 

However, there have been comparatively few empirical studies exploring the demographic variability of harvested populations from a conservation biology or population ecology perspective (FIND A COUPLE THAT DO SOMETHING LIKE WHAT WE ARE DOING). Here, our overarching objective was to quantify the variability of the realized demographic parameters of harvested marine teleost populations. We relied on a database containing data which enabled the estimation of age specific vital rates for `r n.stocks` populations in the north Atlantic and the northeast Pacific Oceans [@charbonneauAgestructuredmarinefishdatabase2022]. These data enabled us to reconstruct the life-tables for the populations and utilize metrics commonly used in conservation biology:  (i.e., population growth rates (ref), doubling time (ref), lifetime reproductive success (ref), and generation time (ref). Furthermore, we evaluated common perceptions about compensatory dynamics, specifically by comparing the strength and magnitude of variability among species with different life histories as well as among populations of the same species that were separated geographically. Our results have implications for sustainable management of exploited marine teleosts and can be used inform the development of rebuilding plans or future status determination for populations that have collapsed. 


# Old stuff we can probably shit can, unless we need more material...

Intro – life history paragraph, environmental variation paragraph, management ties paragraph, goals. 

theoretical expectations related to productivity and life history for various species (e.g. herring vs. Cod) (ties to regional variation in lifetime reproductive rates and doubling time).  

Evidence for specific species to make use of environmental conditions – boom in recruitment.  

How our understanding of productivity is used in a management context – projections, reference points, risk, (ties directly to density dependence figure).  
Species-environment relationship – is it different from what we expect and how does that influence our capacity for management of exploited fishes.  

The under appreciated influence of regional variation in determining recovery potential of exploited teleosts.  - can’t look at a single species and expect it will behave the same way.  


Objectives
  - Quantify the life history variability of exploited marine teleosts
  - Explore regional and taxonomic correlates of life history variability
  - Based on the observed life history, quantify the recovery potential of marine teleosts in the absence of fishing
  