# Methods {#meth}

## Data

These analyses used an existing data repository for 77 stocks from the Northeast Atlantic, Northwest Atlantic, and the North Pacific; including stocks managed by International Council for the Exploration of the Sea; including stocks managed by International Council for the Exploration of the Sea (ICES; `r n.stock.ices`), NOAA (NOAA;`r n.stock.noaa`), and Fisheries and Oceans Canada [DFO, `r n.stock.dfo` stocks, @charbonneauAgestructuredmarinefishdatabase2022; @charbonneauEffectsFishingMortality2022]. Time series started as early as `r min.year` and spanned until `r max.year`, with an average length of `r mn.ts.len` years (range `r min.ts.len` and `r max.ts.len` years). The assessed stocks represented `r num.orders` orders, with the majority of stocks representing Gadiformes (`r num.gads` stocks), Pleuronectiformes (`r num.pleur` stocks) and Clupeiformes (`r num.clup` stocks). The other three orders had relatively few stocks included in the analysis, with `r num.perci` Perciform stocks, `r num.scomb` Scombriform stocks, and just `r num.scorp` Scorpaeniform stock.  The majority of the data came from one of six species: Atlantic cod (*Gadus morhua*;`r num.cod`), (*Clupea harengus*;`r num.her`), haddock (*Melanogrammus aeglefinus*; `r num.had`), pollock (*Pollachius virens*; `r num.pol`), Common sole (*Solea solea*; `r num.sol`), and plaice (*Pleuronectes platessa*; `r num.plat`). 

The repository included age-specific estimates of abundance, weight, biomass, maturity, natural mortality, and fishery removals for each stock (Table \@ref(tab:tab-meta)). Despite uncertainty inherent in assessment processes, each assessment was accepted as a basis for management advice, and thus the time series in the data repository represented the best available understanding of the population dynamics of each stock.


## Population Growth Rates

We used life table reconstructions to calculate survival-at-age and fecundity-at-age over time from the available data series, and applied the Euler-Lotka equation [@lotkaRelationsBirthRates1907] to estimate the corresponding population growth rate ($\lambda$)  in a given year. This allowed us to use information on births, deaths and maturity to describe each stock’s demographics and how they changed over age and over time using a tractable and consistent model, despite variability among stock assessments. 
The discrete time Euler-Lotka equation was first proposed by Euler in 1760 (subsequently published by @moserGesetzeLebensdauer1839) and is a special case of the continuous time demographic model first proposed by Lotka in 1907 [@lotkaRelationsBirthRates1907; @sharpeProblemAgedistribution1911; @lotkaRelationBirthRate1918]:

$$
1 = \sum_{a=\alpha}^{\omega} \lambda_y^{-a} s_{y,a} f_{y,a} dx
$$
Where $a$ is the age, $\alpha$ is the age at first reproduction, $\omega$ is the maximum age, $\lambda$ is the discrete rate of population growth ($\lambda = e^r$), $s_a$ is the survivorship to age $a$, and $f_a$ is the fecundity of individuals of age $a$. This equation is solved for each year ($y$) in which the data are available. Note that the discrete time Euler-Lotka equation can be shown to be the characteristic polynomial of the Leslie Matrix, where $f_0$ is the fecundity of the first age class with mature individuals [@leslieUseMatricesCertain1945, @caswellMatrixPopulationModels2001]. Survivorship-at-age and fecundity-at-age were calculated using the available stock assessment data, which enabled $\lambda$ to be estimated; note that this assumed that each stock represented a discrete population with individual dynamics. 

When calculating survival and fecundity inputs, we considered the last observed age class to be the terminal age, beyond which there was no contribution to productivity. The first age class was age 1 for the majority of stocks (N = `r n.age.1`), where only `r n.age.2.plus` of the stocks had a first age of 2 (N = `r n.age.2`) or greater (N = `r `n.age.3.plus`). For simplicity, we assumed survivorship to the first age class represented by the data to be 1, which results in a slight overestimate of productivity from the Euler-Lotka equation [@pardoMaximumIntrinsicRate2016]. However, we tested back-calculating abundance for the earliest ages using the available time series of age-specific natural mortality rates for several stocks, but this resulted in negligible differences to the annual productivity estimates.

### Fecundity-at-age

We parameterized fecundity as the number of offspring (recruits) produced by each female in each age class rather than as a number of eggs, given that egg production by size, fertilization rates, and egg to age-0 survival rates are unknown. We first calculated an overall rate of recruitment, as the number of recruits produced per kilogram of spawning biomass $RPS_y$:

$$
RPS_{y} = \frac{R_{y}} {SSB_{y-ra}} 
$$

Where $R_y$ is the number of individuals in the youngest age class available for a specific stock (hereafter referred to as recruits) and $SSB_{y-ra}$ is the total spawning stock biomass in year $y$, offset by the age of recruits ($ra$). For example, if the first age class in the abundance time series is 2 years, we assumed that the recruits in 2010 were produced by the spawning stock biomass in 2008 ($SSB_{y-ra}$). 

Then we calculated the total number of recruits produced by each age class ($RPA_{y,a}$) by multiplying the spawner biomass in each age class $SSB_{(y-ra),a}$ by the number of recruits produced per kilogram of SSB

$$
RPA_{y,a} =  SSB_{(y-ra),a} RPS_{y}
$$
Fish are expected to have variability in reproductive success by age (ref, ref). However, we had to make the simplifying assumption that each kilogram of spawning biomass contributed the same to the total total reproductive output, irrespective of age. We calculated the age-specific fecundity ($f_{y,a}$) as the number of offspring produced by each spawner in the stock. The number of spawners in year $y$ and age class $a$ ($NS_{y,a}$) is the proportion of mature individuals in each age class ($Mat_{y,a}$) multiplied by the number of individuals in each age class:

$$
NS_{y,a} = Mat_{y,a} N_{y,a}
$$

and annual fecundity becomes:

$$
f_{y,a} =  \frac{RPA_{y+1,a}}{NS_{(y-ra+1),a}}
$$

Fecundity is offset by one year, as the recruits observed in year $y+1$ enter into the Euler-Lotka formulation in year $y$.

<!-- Fecundity is required to be the number of offspring produced by each female in each age class. Given the uncertainty of both fertilization and egg survival, using the number of eggs at a given length or size is inappropriate.  However, these data do have the number of recruits produced each year, and this can be combined with the spawning stock biomass to obtain an estimate of the number of recruits produced per kilogram of spawning biomass $RPS_{y}$, this is calculated as -->



<!-- Where $SSB_{yot,y-ra}$ is the total spawning stock biomass in year $y$. $R_{y}$ is the number of individuals in the youngest age class available for a specific stock (hereafter referred to as recruits) offset temporally by the age of the recruits. For example, if the age of the recruits ($ra$) is 2 years , we assume that the recruits in 2010 were produced by the spawning stock biomass in 2008 ($SSB_{tot,y-ra}$).  The number of recruits produced by each age class ($RPA_{y,a}$) can then be calculated by multiplying the spawner biomass in each age class $SSB_{y-ra,a}$ by the number of recruits produced per kilogram of SSB -->


<!-- This method does not account for any changes in reproductive success by age, each kilogram of spawning biomass contributes the same to the total total reproductive output, irrespective of their age. Finally, the age-specific fecundity ($f_{y,a}$) is calculated as number of offspring produced by each individual in the stock.  -->

### Survivorship-to-age

The number of animals surviving to each age (survivorship-to-age) depends on age-specific mortality rates (or conversely survival-at-age). Commercially-exploited fishes experience fishing mortality ($F$) once they grow large enough to become vulnerable to the gear (reference). Fishing mortality combines with natural mortality ($M$) to give total mortality ($Z$) affecting each age class in each year. Due to challenges with separability in typical stock assessment models, varying assumptions can be made about natural mortality during stock assessments, where it may be an assumed value for each age (EXAMPLE), allowed to vary over time and by age (EXAMPLE), or input as a constant across ages (EXAMPLE).  We did not explore these differences and used the estimates of natural mortality by age and year found in the data repository (representing outputs from each assessment), which we converted into an annual rate and for input into the Euler-Lotka equation  

The data also contained the number of fish harvested by the fishery each year and for each age. These can be divided by the assessed numbers at age to get an estimate of fishing mortality in each year for each age.

$$
F_{y,a} =  \frac{Catch_{y,a}}{N_{y,a}}
$$
Together, fishing mortality ($F_{y,a}$) and natural mortality ($M_{y,a}$) provide a total mortality estimate ($Z_{y,a}$) for each age in each year.

$$
Z_{y,a} =  F_{y,a} + M_{y,a}
$$
Survival-at-age is simply:

$$
l_{y,a} = 1= Z_{y,a}
$$
Survival-at-age was used to calculate cumulative suvivorship-to-age for input into the Euler-Lotka equation:

$$
s_{y,a} =  s_{y,(a-1)} \times l_{y,(a-1)}
$$
The availability of catch-at-age time series in the data repository meant that fishing mortality and natural mortality rates were separable. Given this method provides separate estimates of $F$ and $M$ it was possible to calculate survival as well as theoretical population growth rates using the $M$ and fecundity ($\lambda_{F=0}$) estimates from the reconstruction. We recognize that the age structure in the underlying time series are still influenced by fishing pressure and that stocks are at varying size. This means that ($\lambda_{F=0}$) does not represent the maximum intrinsic rate of abundance increase [e.g., r_max; CITE]. However, our theoretical annual growth rates in the absence of fishing represent the productivity that the stock could have achieved in each specific year, if there had not been a fishery in that year. 

### Estimation

One limitation of calculating survivorship-to-age and fecundity-at-age using the archived data in the repository is that it is not straightforward to propagate observation error in each time series of data. To ensure that variability did not accumulate into unreasonable predictions for annual stock productivity, we fit the Euler-Lotka model using an iterative minimization process, where predicted abundance in the following year:  

$$
N_{y+1} = \lambda_{y} N_{y}
$$
was compared to the abundance estimate from the stock assessment for the corresponding year ($N_{y+1}$).   

Where necessary, we adjusted the annual age-specific fecundity and natural mortality estimates were adjusted until the $\lambda$ estimate from the Euler-Lotka equation resulted in an abundance time-series estimate ($N_{y+1}$) that was within 5% of the abundance estimates time series output from the stock assessment (median difference was `r med.per.diff`%). The adjustment was performed iteratively, with a step change (for most stocks each step was a change of 0.5%, for some stocks the step size was 0.05%) first made to the natural mortality estimates (applied to each age), if the estimated abundance was not within 5% of the observed abundance estimate this was followed by a step change in the fecundity(applied to each age). This procedure was repeated until the estimated abundance was within 5% of the observed abundance.

This approach ensured that our analyses reflected the same understanding of stock productivity, natural mortality and fecundity as in the current assessments, by effectively treating the abundance estimates in the data repository as the ‘truth’. Although there are inherent limitations to treating stock assessment outputs as observed data [@brooksWhenDataAre2015], these assessments represent the best available knowledge on the population dynamics of each stock. Thus, we consider the abundance time series to be an appropriate benchmark to compare against. The minimization procedure resulted in the final estimates of $\lambda$ being approximately `r med.lam.per.diff`% smaller than the initial estimates. Population growth rates from life table analyses typically decline when variability in the input parameters is accounted for [e.g., CITE Bowlby & Gibson 2020]. However, it is also possible that the removals series used in the stock assessments do not capture all sources of fishing mortality [e.g., unreported catch, bycatch and incidental mortality; CITE]. This would result in the estimates of $\lambda_{F=0}$ being lower than reality, necessitating the slight reductions in fecundity and/or increases in natural mortality during the iterative minimization process. 


## Density Dependence

Life table analyses make no assumptions about population regulation and thus do not incorporate a density-dependent relationship between spawners and recruits [@mcallisterUsingDemographicMethods2001]. However, our estimated productivity parameters could be explored for evidence of density-dependence by modelling each stock’s annual population growth rate against relative stock size (expressed as a proportion of maximum abundance) in the same year. Negative density dependence is observed when $\lambda$ increases as abundance declines [CITE] which is the type of compensatory response described by typical spawner-recruit relationships (ref, ref). Positive density dependence occurs when λ declines with increasing abundance, which is also called an Allee effect when it occurs at low abundance (ref, ref). Density independence occurs when λ shows no relationship with changes in abundance. We evaluated both the realized productivity estimates ($\lambda_{F>0}$) and the theoretical productivity values excluding the impact of fishing mortality ($\lambda_{F=0}$).


Life table analyses make no assumptions about population regulation and thus do not incorporate a density-dependent relationship between spawners and recruits (Reference?). However, the data could be explored for evidence of density-dependence by modelling each stock's estimated annual population growth rate against the relative stock size (proportion of maximum abundance) that year. This was done twice, once using  ($\lambda_{F=0}$) and once using ($\lambda_{F>0}$).  Negative density dependence is observed when $\lambda$ increases as abundance declines, positive density dependence occurs when $\lambda$ declines with increasing abundance, while density independence is observed when $\lambda$ is not impacted by changes in abundance.

We used Generalized Additive Mixed Models (CITE MCGV and WOOD) to describe potential relationships, where the overall effect and the effect for each stock was modelled as

\begin{align}
\lambda_{i,j} \sim N(0,\sigma^2_{i,j}) \\
E(\lambda_{i,j}) = \mu_{i,j} \\
log(\mu_{i,j}) =  Prop_{i} + Stock_{j}  \times Prop_{i} \\
Stocks_{i,j} \sim N(0,\sigma^2_{Stocks})
\end{align}


The interaction was modeled using the *fs* basis in the mgcv package in R, which treats the smooth curves as random effects and is used when a factor has a large number of levels (CITE!). Although we explored various model formulations and alternative error distributions,  all models had similar challenges overcoming either the underlying non-normality or the heteroskedasticity of the data. Given these challenges we do not use the model to determine the statistical significance of the trends. This approach was preferred to fitting simple loess smooths to individual data series, because we were able to better capture the global relationship in addition to providing a relative metric of variability among the stocks. 

For a reconstruction of time series as undertaken here, the maximum value of $\lambda$ is constrained at higher abundances because the maximum abundance is a known value (e.g., the maximum possible $\lambda$ at 50% of the maximum abundance is 2, at 25% is it 4, and at 100% it is 1). Conversely, the minimum value of $\lambda$ will be constrained at lower abundances (e.g., $\lambda$ must be $\ge$ 1 when the stock is at it's minimum observed abundance). As a result, at the maximum abundance $\lambda$ will be $\le$ 1, at the minimum $\lambda$ will be $\ge$ 1, and, on the natural scale, higher variability in $\lambda$ values at low abundances should be relatively common.

<!-- The interaction was modeled using the *fs* basis using the mgcv package in R, this treats the smooth curves as random effects and is used when a factor has a large number of levels (CITE!).  Various alternative modelling methods were explored (various model formulations, alternative error distributions, etc.) but all models had similar challenges overcoming either the underlying non-normality or the heteroskedasticity of the data. As such, the uncertainty surrounding the model output should be treated with caution, while we discuss the general trends this model provides we attempted to avoid discussion of the statistical significance of the trends. -->

## Recovery Potential

There are numerous demographic parameters that can be derived from the outputs of the life table reconstruction [CITE]. Here we focus on three that are strongly linked to recovery potential:  doubling time, lifetime reproductive success, and generation time. Comparing the median time frame over which abundance can double gives a good indication of relative productivity among species and stocks. Monte Carlo draws from the observed distribution of fecundity and natural mortality were used in a projection simulation to estimate the doubling time for each stock.  Lifetime reproductive success, also called the net reproductive rate, describes the average number of female spawners produced by one female spawner throughout her lifetime. Values greater than 1 suggest a stock would tend to increase, values less than 1 suggest a stock would tend to decline, and a value of exactly 1 indicates that the average female has produced sufficient offspring over their lifetime to only replace themselves. 

Generation time is an alternate indicator for the relative reproductive rate of a stock, where shorter generation times are associated with faster population growth. Here, we calculated generation time as  is calculated for each cohort and is the mean age of spawners that produced recruits [CITE]. Values of both the lifetime reproductive rate and generation time were derived for each complete cohort, which meant we could also evaluate changes in reproductive capacity over time for each stock. Additionally, we compared theoretical reproductive potential and generation times from life history characteristics alone ($F=0$) with those expected under current fishing mortality ($F>0$), as detailed in section 3.2.2.

<!-- There are numerous demographic parameters that can be derived from the outputs of the life table reconstruction. Here we focus on three that are strongly linked to recovery potential: doubling time, lifetime reproductive success, and generation time. The doubling time estimates were performing using a simulation technique based on the fecundity and natural mortality estimates used to calcualte $\lambda$.  Lifetime reproductive success describes the average number of spawners produced by one female spawner throughout her lifetime. A value greater than 1 indicates that the average female has produced sufficient offspring over their lifetime to replace themselves. Generation time here is calculated for each cohort and is the mean age of spawners that produced recruits. -->

### Doubling Time

The annual fecundity and natural mortality values varied considerably for each stock. To account for this variability when evaluating recovery potential, we used a simulated stock projection. For `r n.dt.sims` simulations, we took a random sample of the annual values for fecundity and natural mortality, used the life table reconstruction to estimate $\lambda$, and calculated abundance in the following year. Abundance of each stock was projected over `r `n.sim.years` years, and the proportion of the simulations in which the stock size had doubled was recorded each year. We considered stocks to have high recovery potential if 75% of simulated trajectories doubled, medium potential if 50-74% of simulations doubled, and low recovery potential if < 50% of simulated trajectories doubled, calculated at 10 and 20 years into the projection. For simplicity, we did not incorporate density-dependent effects (e.g., potential population decline as abundance exceeds carrying capacity) or any correlation (either temporally or between fecundity and natural mortality). Once a population had doubled, it was considered to have remained at that abundance or greater for the remainder of the projection. This means that the metric gave the earliest possible doubling time for each simulation, assuming no future fishing mortality.  

### Lifetime Reproductive Success 

Lifetime reproductive success ($R_0$) was calculated for each cohort in which fecundity and natural mortality were available for complete cohorts (i.e., cohorts in which all available age classes are represented). For species with a long lifespan, this meant that lifetime reproductive success was more indicative of expectations from earlier in the exploitation history, rather than more recent years. 

It was calculated both by using only natural mortality component ($F=0$) and with the combined effect of natural mortality and fishing mortality ($F>0$), respectively. This provided an understanding of the reproductive potential from observed stock characteristics alone, and how it changed with fishing pressure. $R_0$ was calculated for each cohort as:

$$
R_0 = \sum_{x=\alpha}^{\omega} s_x f_x
$$
This formulation ignores any contribution from a plus group, by assuming that the last observed age in the data represents the longevity of the cohort. This simplifying assumption will cause a slight values negative bias in the values, given that the oldest sampled age class is typically younger than the theoretical longevity of a given species based on growth (CITE). 

**NOTE to Y'all: Here we are treating the plus group as effectively 'terminal', i.e., it assumes that after the last age class the individuals make no contribution, which means these values are probably a bit low, but at this age they really aren't making much of a contribution on average**.

### Generation Time

We defined generation time as the mean age of the spawners that produced the observed recruits in a cohort [$T_G$,@caswellMatrixPopulationModels2001]. 

$$
T_G = \frac{\sum_{x=\alpha}^{\omega} x s_x f_x}{\sum_{x=\alpha}^{\omega}  s_x f_x}
$$

