# Results {#reses-peses}

## Population growth rates ($\lambda$)

The overall median population growth rate when excluding the effects of fishing ($\lambda_{F=0}$) was `r med.lambda.F0`, which represents a latent capacity for population growth of only `r med.r.F0`% annually. Aggregating over years, the population with highest median theoretical population growth rate was Atlantic cod in the Irish Sea (median $\lambda_{F=0}$ = `r max.median.lam.nf`) and the lowest was pollock in the Gulf of Alaska (median $\lambda_{F=0}$ = `r min.median.lam.nf`).  When the effects of fishing was were accounted for, the overall median population growth rate ($\lambda_{F>0}$) declined to `r med.lambda.F`, which would correspond to overfishing by  `r -med.r.F`% annually. The realized range of population growth rates was much narrower, as would be expected from managed stocks, where a typical goal is to maintain stock size at or above a specific biomass reference point [CITE]. Indeed, median $\lambda_{F>0}$ was below one the majority of the time for `r prop.usually.lt.1.fish`% of the stocks, suggesting that stocks were being managed in a way that essentially eliminated their capacity for abundance increase in more than half of the years in the data. However, many of the populations included in our analysis experienced infrequent large recruitment events that resulted in high $\lambda_{F>0}$ estimates (Figures \@ref(fig:lambda-bx-6-fig) and \@ref(fig:lambda-bx-other-fig)). For example, while Gulf of Alaskan pollock has the lowest median $\lambda_{F=0}$, it's mean $\lambda_{F=0}$ was `r mean.nf.of.min.median.lam.nf`, and when the effects of fishing are included this population had the $8^{th}$ highest mean $\lambda_{F>0}$ (`r mean.fish.of.min.median.lam.nf`) in this analysis. Consequently, the overall mean realized growth rate $\lambda_{F>0}$ for the populations in this analysis remained slightly greater than one. On average, population growth tended to compensate for declines in other years, maintaining a net positive overall productivity for most of these stocks.

Mean $\lambda_{F>0}$ was lower than the median for just `r n.stocks-n.mn.higher.med.fish` of the `r n.stocks` populations in this analysis, and the mean $\lambda_{F>0}$ was less than one for only `r num.mn.lambda.fish.lt.1` of the `r n.stocks` populations. The majority of the populations experiencing these consistent declines (N = `r n.nw.ice`) were in the central or NW Atlantic, and included `r n.cod.low.mn`  of the `r n.cod` Atlantic cod (*G. morhua*) populations in this analysis.

There were regional and species specific trends in both $\lambda_{F=0}$ and $\lambda_{F>0}$. Haddock (*M. aeglefinus*) and Atlantic cod populations exhibited some of the highest variability in population growth rates, both over time and among stocks, with $\lambda_{F=0}$ values exceeding 2 for multiple years and for multiple populations for both species (Figure \@ref(fig:lambda-bx-6-fig)). For these two species, the variability of population growth rate declined as you moved from the eastern Atlantic to the western Atlantic demonstrating that growth rates tended to be more consistent in the eastern as opposed to western Atlantic (Figures \@ref(fig:lambda-bx-6-fig) and \@ref(fig:lambda-sd-fig)). The pattern was most pronounced for Atlantic cod, with populations in the eastern Atlantic tending to have relatively low within population variability. A comparison between populations found in the western and eastern Atlantic was possible for two other species, Atlantic herring (*C. harengus*) and pollock (*P. virens*).  Surprisingly, the variability of $\lambda$ between the Atlantic herring and pollock populations was much lower (Figure \@ref(fig:lambda-bx-6-fig)) than for either haddock or Atlantic cod and there were no clear differences between regions for these two species (Figure \@ref(fig:lambda-sd-fig)). Two other populations, sand eel (*A. tobianus*) and Norway pout (*T. esmarkii*), in the North Sea had highly variably $\lambda's$, though notably less variable than the Haddock and Atlantic cod $\lambda's$ in this area (Figure \@ref(fig:lambda-bx-other-fig)). For the remainder of other populations in this analysis, years in which the value of $\lambda_{F=0}$ were elevated (e.g., above $\approx$ 1.5) were more rare. Exceptions included whiting (*M. merlangus*) in the Celtic Sea, summer flounder (*P. dentatus*) and scup (*S. Chrysops*) in the western Atlantic, and the Gulf of Alaska pollock (*G. chalcogrammus*) population in the Pacific Ocean (Figure \@ref(fig:lambda-bx-other-fig)).

## Density Dependence

Overall, the data suggested that negative density dependence was common as both $\lambda_{F=0}$ and $\lambda_{F>0}$ increased as abundance declined (Figure \@ref(fig:dd-overall-plt)). Changes in the rate of population growth were more pronounced at low and high abundance levels; the relationship from the fitted GAMM was essentially flat when relative abundance ranged between 40-70% of maximum. This suggests that there was a surprisingly large range of population abundances that would not be expected to exhibit strong compensatory dynamics. The predicted population growth rate excluding the impacts of fishing ($\lambda_{F=0}$) only declined below one when the populations approached their maximum observed abundance ($\gtrsim$ `r pa.lam.nf.at.one`%). However, when accounting for fishing mortality ($\lambda_{F>0}$), the modelled relationship dropped below one when the population abundance exceeded approximately `r pa.lam.fish.at.one`% of their maximum abundance. At lower abundances, the model estimated population growth rate excluding fishing ($\lambda_{F=0}$) increased more slowly than realized population growth rates ($\lambda_{F>0}$) likely due to reductions in fishing mortality at low abundance. However, the fitted values never converged, suggesting that some fishing mortality remained even at very low abundance (Figure \@ref(fig:dd-overall-plt)).

As expected, there was generally an increase in the variability of the $\lambda$ estimates as abundance declines, largely driven by an increase in the magnitude of the maximum value of $\lambda$ and a small increase in the frequency of low $\lambda$ values (Figure \@ref(fig:dd-overall-plt)). While there was a consistent overall pattern, the estimated random effects demonstrated substantial variability among stocks in the strength of negative density dependence. For examples, populations in the western Atlantic (particularly Atlantic cod) and Alaska had some of the lowest $\lambda_{F=0}$ estimates at low abundance, while several populations in the North Sea (including Atlatnic cod) had among the highest $\lambda_{F=0}$ estimates at low abundance (Table \@ref(tab:tab-lambdas)).  Of the `r n.bl.40` populations that had declined below 40% of the maximum abundance, only `r n.low.40.nf` of the populations had $\lambda_{F=0}$ estimates < 1 at 40% of their maximum abundance; when the effects of fishing were included `r n.low.40.nf` of the populations had $\lambda_{F>0}$ estimates below 1 (Table \@ref(tab:tab-lambdas)).

The vast majority of populations the lowest values of both $\lambda_{F=0}$ (`r n.low.lam.at.max.nf` of `r n.stocks`) and $\lambda_{F>0}$ (`r n.low.lam.at.max.fish` of `r n.stocks`) were found near the maximum abundance in the time series, this conforms to the expectations of this type of historical reconstruction and population dynamics theory (i.e., negative density dependence; see Supplemental Figures \@ref(fig:dd-nf-stock-plt) and \@ref(fig:dd-fish-stock-plt)). However, Atlantic cod in the Northwest Atlantic comprised `r n.cod.lam.not.at.max.nf` of the `r n.stocks - n.low.lam.at.max.nf` populations in which the lowest population growth rates were observed at abundances markedly below the maximum. These Atlantic cod populations seemed to have the least compensatory capacity at relative abundances between `r pa.low.cod.min` and `r pa.low.cod.max` even when excluding the impacts of fishing mortality. For two of the `r n.stocks - n.low.lam.at.max.nf` populations, the lowest $\lambda_{F=0}$ estimates were less than 0.005 smaller than the estimate at the maximum abundance, indicating extremely similar compensatory capacity over the majority of observed stock sizes. The declines in $\lambda_{F=0}$ for the other four populations were more pronounced (Supplemental Figure \@ref(fig:dd-nf-stock-plt)), ranging from `r low.4.lam.40.nf` to `r low.lam.40.nf` (Tables \@ref(tab:tab-lambdas) and \@ref(tab:tab-lamda-diffs)).

## Recovery Potential

Lifetime reproductive output and generation length were estimated for each cohort in which data were available, population decline would be assured from lifetime reproductive rates consistently below 1. When excluding fishing mortality, the overall median lifetime reproductive output, (i.e., the number of females spawners per female spawner) was `r r0.med` (mean = `r r0.mn`; Figure \@ref(fig:r0-6-plt)). When realized fishing mortality was accounted for, the median reproductive output dropped to `r r0.med.fish` (mean = `r r0.mn.fish`). This difference between the mean and median for stocks experiencing exploitation, again highlighted the importance of large reproductive events to persistence by maintaining the latent capacity for population growth (Figure \@ref(fig:r0-6-plt)). For species which were found across the North Atlantic, the lifetime reproductive output when excluding fishing mortality tended to decline from east to west, which again was most evident for the Atlantic cod populations. While the reproductive potential of cohorts within a population could be highly variable, there were no clear temporal trends in $R_0$ (Figures \@ref(fig:r0-nf-ts-plt) and \@ref(fig:r0-fish-ts-plt)).

Generation length (calculated as the mean age of spawners contributing to a recruit cohort) tended to become more similar with fishing pressure included both among stocks and among species (Figures \@ref(fig:gl-6-plt) and \@ref(fig:gl-other-plt)). This is an expected outcome of reduced survivorship-to-age. However, there were regional and interspecific patterns that were unexpected. For example, Atlantic herring is typically considered to be a short-lived species yet its generation length in the Central and western Atlantic tended to be higher than the generation length of Atlantic cod and haddock (especially for the populations in the eastern Atlantic; (Figure \@ref(fig:gl-6-plt)). Similar to lifetime reproductive output there were no obvious temporal trends in the generation length among cohorts for the populations in this analysis  (Figures \@ref(fig:gl-nf-ts-plt) and \@ref(fig:gl-fish-ts-plt)).

Based on simulated stock trajectories, the recovery potential in the absence of fishing was relatively high for the majority of species (Figure \@ref(fig:dub-time-map)). Of the `r n.stocks` populations in this analysis, `r n.dub.10` had at least 75% of the simulations double in size withing 10 years, which increased to `r n.dub.20` populations by 20 years (Figure \@ref(fig:dub-ts)). Conversely, there were clear regional trends in stocks with low recovery potential. Of the `r n.not.dub.20` populations in this analysis in which < 50% of simulations doubled in size after 20 years, `r n.alaska.slow` were in Alaska and `r n.nwa.slow` in NAFO Regions 2-4 in the western Atlantic. This meant that `r prop.slow.alaska`% and `r prop.slow.n24`% of assessed stocks in Alaska and NAFO Regions 2-4, respectively, had low recovery potential. This contrasts to only `r n.nea.slow` of the `r n.nea` populations in the eastern Atlantic with a low recovery potential within 20 years in the absence of fishing (Figure \@ref(fig:dub-time-map)).

Recovery potential was intrinsically linked to both the magnitude and variability in annual population growth rates. The recovery potential was influenced both b$\lambda_{F=0}$ and the variability in $\lambda_{F=0}$. Populations with a median $\lambda_{F=0} < 1$  had moderate (defined as populations in which 50-75% of the simulations doubled within 20 years) to high (> 75% doubled in size within 20 years) recovery potential whenever the standard deviation in $\lambda$ was $\gtrsim$ 0.4 (Figure \@ref(fig:dub-vs-sd)). Populations with a median $\lambda_{F=0}$ near 1 and with low variability tended to be stocks with low recovery potential.
 