# DISCUSSION {#disin}

@hobdayEcologicalRiskAssessment2011 is a paper using life history for closely related species.

Exploring demographic variability and realized compensatory responses in marine fish populations highlight several instances where stock dynamics do not conform to expected theoretical relationships, which has potentially serious implications for future management. Although most stocks exhibited a latent capacity for annual growth, and exhibited evidence for negative density dependence, overall theoretical growth rates in the absence of fishing were surprisingly close to 1, with several stocks having no apparent capacity for abundance increase in the majority of years. Quota-based fisheries management strategies often aim for neutral (50%) risk in the probability of population decline when setting harvest advice (ref, ref), so it was not unexpected that realized population growth rates centered around 1. 

What was unsettling was how little capacity for increase these stocks seemed to retain when excluding the effects of fishing (i.e., $\lambda_{F=0}$). If fishing ceased, future recovery was likely within 20 years whenever the median  $\lambda_{F=0}$ was greater than 1.06 or the standard deviation of lambda was greater than 0.2. This applied to only ADD SOMETHING and none of the highest trophic level species. Widespread distributions, high egg production per female, and broadcast spawning strategies have all contributed to the impression that marine fishes should have very high potential for annual population growth [(CITE)]. When environmental variation results in favorable conditions, stocks are anticipated to exhibit high survival, resulting in large recruitment events or higher overall survival [(CITE)]. While we found indirect evidence of this, in that populations with high variability in  $\lambda_{F=0}$ also had high recovery potential, the magnitude of intra-species variability did not conform to expectations from conventional life-history theory [@kindsvaterTenPrinciplesEvolutionary2016]. For example, Atlantic herring are a small, relatively short lived, low trophic level pelagic species [CITE]. Their life history characteristics are considered to result in highly variable population growth potential which should allow them to exploit favorable environmental conditions and increase quickly in abundance [CITE]. However, the variability of  $\lambda_{F=0}$ for Atlantic herring was much lower than for the higher trophic level and longer lived Atlantic cod and haddock stocks in the same region. Furthermore, these three species co-occur in the NE Atlantic [CITE] and the timespan of data collection was similar, suggesting they likely experienced similar variability in oceanographic conditions. Other small pelagic populations, such as $A. tobianus$ and $T. esmarkii$ were characterized by higher  $\lambda_{F=0}$ values, which conforms to theoretical expectations for small, low trophic level species. However, these two stocks were found in the North Sea, which appears to be an environment in which high variability in  $\lambda_{F=0}$ is commonplace for harvested stocks. In addition, while stocks with a high variability in $\lambda_{F=0}$ do have years with very high population growth, these events happen at irregular intervals, even when populations are at low abundances. Contrary to assumptions from typical stock-recruit relationships [CITE], stocks do not necessarily exhibit increased compensatory capacity when at low abundance. These data suggest that while most stocks have the capacity for rapid abundance increase, they only do so occasionally even when at low abundance. Thus, accounting for both the magnitude and frequency of years with high population growth become key components during the development of fisheries advice, as well as for the development of recovery plans and conservation targets [CITE ref new Fisheries act stuff? Precautionary approach stuff?].

NOTE THAT THE BECAUSE WE ASSUMED FISHERY REMOVALS WERE CORRECT COMBINED WITH THE PRODUCITIVTY PARAMETERS HAVING RESULTED IN LAMBDA VALUES THAT ARE 5% LOWER, IF THAT DECLINE IN LAMBDA WAS DUE TO FISHING, OUR PROJECTIONS, GENERATION TIME, AND R0 VALUES WOULD ALL BE SOMEWHAT CONSERVATIVE AS TO GET THAT LOWER LAMBDA VALUE WE ATTRIBUTED THIS TO THE PRODUCTIVITY OF THE SYSTEM BEING LOWER, WHEREAS ATTRIBUTING THAT DIFFERENCE SOLELY TO FISHING WOULD HAVE HAD NO IMPACT ON THE NATURAL MORTALITY OR FECUNDITY

Our best understanding of productivity in these assessed fish stocks suggests that equilibrium theory and general life history characteristics (e.g. longevity, trophic level) are poor predictors of population growth rates and recovery potential. For stocks that have collapsed or are considered to be at very low abundance, it would be prudent to evaluate lifetime reproductive rates prior to developing harvest advice. Numerous stocks in our analysis had no apparent capacity to increase in abundance even in the absence of fishing, which would assure further declines if harvesting continued. For example, there were seven populations in which $\lambda_{F=0}$ at 40% of maximum abundance is below 1, five of these populations are found in the NW Atlantic, and five of these are in the Gadus genus (*G. morhua* [3] and *G. chalcogrammus* [2]). These stocks exhibited characteristics much more similar to endangered populations [e.g., several Atlantic salmon Designatable Units in Canada, CITE COSEWIC REPORT], which can also have lifetime reproductive rates < 1 [Gibson refs, CITE], in addition, there was little evidence of negative density dependence for these stocks. In our analysis, the most marked example was Atlantic cod in the NW Atlantic. We have little understanding of how large these Atlantic cod stocks would have been originally. The maximum abundance and thus the magnitude of decline used for our analyses represents the outcome of > 100 years of industrial fishing [Cite Rose book maybe?, others]. Similar to salmon, extreme abundance decline combined with changes in the environment [Cite cold water and seals] may have resulted in these stocks having little latent capacity for growth or recovery. Indeed, it has been suggested that the SGSL cod population will go extinct unless natural mortality declines significantly [CITE Doug’s predator pit stuff], a conclusion supported by our analysis. However, the low recovery potential of Atlantic cod was no longer observed as one moves towards the eastern Atlantic, with stocks around mainland Europe all exhibiting high recovery potential. As with $G. chalcogrammus$, this indicates that regional variability must factor strongly into a species’ ability to withstand fishing pressure. Given that variability in population growth potential among stocks could be substantially greater than among species (e.g., compare the variability of $\lambda$ between Atlantic cod and Atlantic herring), life history characteristics and/or trophic level appear to be poor predictors of how marine teleosts will respond to fishing. This problem would compound for less data-rich stocks, in that typical assumptions made for data-poor assessments (give examples of assessment methods) would be more likely to lead to inappropriate harvest advice. That life history characteristics did not link strongly to expected productivity is extremely concerning, given the need for sustainable fisheries management of data-poor stocks [CITE] to mitigate risks of overfishing across the globe [CITE].

Our life-table reconstruction enables the underlying demographic rates to be estimated for populations with sufficient age-structured data, this provides an opportunity of understanding the dynamics of these populations using concepts developed in conservation biology and ecology. In doing so, our optimization procedure assumed that both the estimates of abundance and the fishery removals from the stock assessment are correct. Although these assumptions are unlikely to be fully met [CITE], it is important to remember that harvest advice is being derived for these stocks under the same general assumptions. Thus, our analyses reveal that current assessments can be based on vastly different understandings of productivity and the potential for population growth for the same species, even when incorporating similar elements to describe population dynamics (e.g., equilibrium theory). Our analysis suggests that management advice might be fairly accurate for stocks that aren’t overly variable or those that retain high latent capacity for population increase. Low variability would suggest that the stock is not overly influenced by variation in environmental conditions [or that there was little environmental variability in the ecosystem, CITE], while high latent capacity for population increase could indicate the opposite [CITE]. However, it is not immediately apparent what conditions (environmental, ecological and/or anthropogenic) might be the primary determinants of population growth rates for a given cohort or system. Our findings underscore the need for alternative frameworks in which to derive advice, particularly those that incorporate consideration of interspecies relationships and/or environmental conditions under the umbrella of ecosystem-based fishery management [CITE]. They also underscore the need to collect stock-specific data on marine teleosts, rather than using species-level information from global repositories [e.g., Fishbase, Fishlife, CITE] or assuming values from closely related species to derive harvest advice [CITE]. 

SOMETHING ABOUT EXPLOITATION HISTORY IF THERE ISN'T ALREADY.
MISSING CAVIATS (e.g. exploitation history, assumptions related to assuming model fit and fishing is right, )

Looking to the future, ….. 


---- End Heathers edits that need tidied up---





Here we deconstructed the ecological demographics of numerous harvested marine fish populations . In general, these populations have latent capacity for growth and, even when accounting for the influence of fishing, these growth rates are very close to 1 in general.  

For every population in this analysis the $\lambda_{F=0}$ at the minimum observed abundance was estimated to be greater than one; suggesting all of the populations have the potential for some degree of recovery given enough time when there is no fishing mortality. However, there are seven populations in which $\lambda_{F=0}$ at 40% of the maximum abundance is below 1, five of these populations are found in the NW Atlantic, and five of these are in the Gadus genus (*G. morhua* (3) and *G. chalcogrammus* (2)). For both of these Gadus species, there are examples of populations in which the latent capacity for growth is far more robust.  For example, *G. chalcogrammus* is one of the largest fisheries in the world and the vast majority of the landings are from the Eastern Bering Sea population which has a high latent capacity for growth. However the $\lambda_{F=0}$ estimates for two neighboring populations in Alaska are much lower, and it is likely that these populations experience much lower fishing pressure because of their low latent capacity for growth.  

In contrast, in the NW Atlantic, several *G. morhua* populations supported large distant waters fishery for centuries (citations), however the data used in this analysis indicated the majority of the stocks in the NW Atlantic have minimal recovery potential. The maximum abundance used for these populations was likely a small fraction of the historic maximum abundance of these stocks, primarily due to over fishing by the industrial fishery that developed in the latter half of the 20th century (Cite Rose book maybe?, others). Here it is likely that the fishery induced changes to the population, which combined with changes in the environment (Cite cold water and seals) has resulted in these populations having little latent capacity for growth or recovery. Indeed, it has been suggested that the SGSL cod population will go extinct unless natural mortality declines significantly (Doug’s predator pit stuff); the results of this analysis largely align with these suggestions given the low recovery potential of this stock and it's extremely low latent capacity for growth. However, as one moves towards the eastern Atlantic, the low recovery potential of *G. morhua* populations was no longer observed, with stocks around mainland Europe all having a high recovery potential. As with *G. chalcogrammus*, this indicates that regional variability is a factor in the ability of populations to withstand fishing pressure. While some Gadus populations have an ability to withstand large fisheries due to their latent capacity for growth, the life-history at a species level is insufficient to predict how a population will respond to fishing. Moreover, this analysis is relevant for only the period under study, the recovery potential assumes that the underlying population demographic rates in the future will be similar to those observed in the past. However, as is likely the case with the *G. morhua* stocks in the NW Atlantic, the response for a population may change over time due to environmental, ecological, and anthropocentric factors (CITE!).

More generally, we observed that populations with high variability in $\lambda_{F=0}$ have a high recovery potential, however, this variability does not necessarily follow on from the expectations of conventional life-history theory [@kindsvaterTenPrinciplesEvolutionary2016]. For example, *C. harengus* are a small, relatively short lived, low trophic level pelagic species (Cite!), based on life-history theory *C. harengus* should exhibit highly variable population growth potential in which they ‘exploit’ opportunities within the environment (CITE). However, the variability of $\lambda_{F=0}$ for the *C. harengus* populations was much lower than the *G. morhua* and *M. aeglefinus* populations found throughout the NE Atlantic. Other small pelagic populations, such at *A. tobianus* and *T. esmarkii* do have elevated  $\lambda_{F=0}$ as life-history theory would expect for small low trophic level species. However, caution would be advised in suggesting that other populations of these species would have similar population dynamics, especially given these two populations are found in the North Sea, which appears to be an environment in which high variability in $\lambda_{F=0}$ is commonplace. In addition, while stocks with a high variability in $\lambda_{F=0}$ do have years with very high population growth, these events happen at irregular intervals, even when populations are at low abundances. As such, for populations in which recovery plans and conservation targets are being developed, the developers must account for *both* the magnitude and the frequency of these events. Populations do not *always* increase at their maximum intrinsic rate of growth when at low abundance, but they may have the ability to do so occasionally.

The optimization procedure used for the life-table reconstruction herein assumes that both the estimates of abundance and the fishery removals from the stock assessment are correct. Given the underlying assessment models estimate biomass and abundance from fishery independent surveys that have undergone multiple years of peer review, we are confident that the underlying trends captured by the assessments provide a reasonable snapshot of the population dynamics of these population. However, it is likely that the fisheries removals used in the stock assessments do not capture all the mortality due to fishing, unreported fishing, bycatch and incidental mortality could all result in higher fishery removals than estimated in the assessments (CITE). This would result in the estimates of  $\lambda_{F=0}$ being lower than reality; ‘missing’ mortality would have been accounted for by reductions in fecundity and/or an increase in natural mortality. The optimization routine resulted in a median decrease in the no-fishing $\lambda_{F=0}$ estimates of approximately 6.8% when compared to the non-optimized estimates; the directionality of this change is consistent with fishing mortality being underestimated. Thus, $\lambda_{F=0}$ is likely an underestimate of the latent capacity for growth of these populations, this magnitude of this bias in any year would be dependent on the level of unaccounted for fishing mortality a population experienced.

Here we provide an overview of the population growth and recovery potential of numerous harvested marine fish populations. There is a latent capacity for growth for most populations and the majority of the populations appear to have the ability to recover relatively quickly if fishing mortality is reduced to low levels. However, there can be significant intra-species variability which may be related to environmental, ecological, and anthropocentric factors. This makes it difficult to use species level life-history traits to predict the population dynamics of specific populations.  The life-table reconstruction enables the underlying demographic rates to be estimated for populations with sufficient age-structured data, this provides an opportunity of understanding the dynamics of these populations using concepts developed in conservation biology and ecology.



## Ignore this, unless something is in here you want to pull into discussion

I think we disagree with @kindsvaterTenPrinciplesEvolutionary2016 because we can't generalize based on life-history very easily (cod haddock herring).

Looks like density dependence is real. Dave's pet theory is there is solid evidence of density dependence for many stocks above around 0.4, below 0.4 the evidence suggest that density dependence weakens for some stocks, BUT, some stocks have an ability to very occasionally very spectacularly take advantage of the environment.  But not all stocks and species have this ability and the strength and frequency seems to be influenced by where you live and what species you are. Little evidence for high lambda for most stocks in the NW Atlantic, while many stocks assessed in the North Sea had anomalously high lambdas in 1 or more years. Cod show this  perfectly....

Looks like the median lambda is around 0.2 at low abundance (mean is much higher because outliers) for many stocks. So potential growth at low abundance is around 20%, tends to trend towards 0 as you approach the maximum observed abundance. This is very interesting b/c on average is suggests that the maximum observed abundance may be a reasonable proxy for the carrying capacity of a stock. Of course there is a great deal of variability around this, which may be related to the timing of the start of the time series in relation to historical fishing activity, fishing pressure, environmental variability, etc... but still it is kinda interesting.  

The recovery potential for some species is tied to the variability in their growth rate... Based on historically observed lambdas, all the Haddock stock in this analysis were likely to double in size within a decade of fishing cessation. The worst situation is low lambda + low variability... you can have a low lamda 'most of the time', but if highly variable the stock can take off (this in many ways is what fisheries science is based on)... Also of note these large events do tend to be far more likely when abundance is < 40% of maximum (of course this would be in part because it's easier to go from having \$10 to \$20 than it is to go from \$1,000 to \$2,000). 

Idea- realized productivity of cod/haddock has been highly variable. But from life history theory you would have expected that to be herring/smelt. Episodic recruitment events. (boom and bust?) not population boom but more like a baby boom.  

Likelihood of stock collapse related to life history characteristics, maybe reframe relative to large productivity events of cohorts – link to idea of cod/haddock above. No expectation that intersection between life history traits and environmental conditions to result in such marked differences among populations within a species in realized productivity.  

Center around the idea of equilibrium theory? That management might be fairly good for stocks that aren’t very variable, but when you make a decision based on averages you can make really bad ones.  

By ignoring the density dependence patterns observed in this analysis, the doubling time analysis would overestimate the doubling time for stocks that were at low abundance with classic negative density dependence dynamics, while it would underestimate it for stocks with positive density dependence. Here perhaps talk about infrequent big events and how using a theoretical rmax within a logistic model isn't a good idea because this will way over-estimate recovery potential at low abundance.

The optimization procedure assumes that both the estimates of abundance and the fishery removals from the stock assessment are correct. *A couple sentences about why fisheries removals may be underestimated*. This would result in the estimates of the $\lambda$ excluding fishing mortality in this analysis being lower than reality, as this 'missing' mortality was accounted for by reductions in either fecundity or an increase in natural mortality. The optimization routine resulted in a median decrease in the no-fishing $\lambda$ estimates of approximately `r med.lam.per.diff`%, the overall directionality of this change is consistent with fishing mortality being generally underestimated.

Fisheries appear to slightly weaken the effects of density dependence overall. Maybe due to fisheries having positive density dependence? Seemingly below around 0.5 fishing leads to a positive lambda, below 0.5 it is a negative lambda... that's kinda kooky cool!

The stocks which reached very low abundance (< 10% of maximum) tended to have high values of lambda, suggesting strong compensation in stocks when they are at extremely low abundance. Oddly, the path to this isn't linear, and positive density dependence (or at least density independence was evident between 10 and 40% of maximum abundance).  

Probably something worth citing in here @thorsonPredictingRecruitmentDensity2020


While alternative frameworks have been suggested and are being implemented globally, (e.g., Ecosystem Based management) the uptake of these methods has been relatively slow due to a lack of mechanistic understanding, a lack of data, and the more complicated nature of the science advice alternative methods provide. 

