---
title: |
   "Variability in the recovery potential of globally exploited teleosts "
french_title: "Titre ici (*Nom latin de l'espèce*)"
author: |
  David. M. Keith^1^ 
  Freya M. Keyser^1^
  Julie M. Charbonneau^2^
  Heather 'The Boss' Bowlby^1^
author_list: "Keith, D.M., Keyser, F.M., Charbonneau, J.M., Bowlby, H.T.B."
address: |
  ^1^Bedford Institute of Oceanography\
     Fisheries and Oceans Canada, 1 Challenger Dr.\
     Dartmouth, Nova Scotia, B2Y 4A2 , Canada\
  \smallskip
  ^2^Simon Fraser University\
     Department of Biology\
french_address: |
  
month: ""
french_month: ""
year: 2024
report_number: nnn
region: "Maritimes Region"
french_region: "Maritimes Region"
isbn: ""
cat_no: ""
citation_other_language: ""

abstract: |
  Marine fishes were once believed to be extremely resilient to the effects of fishing, but this view has changed over time, due in part to the collapse of large fisheries and a lack of rebuilding of some populations after these collapses. This has lead to questions about the underlying assumptions used in the management of these populations and the impact of environmental factors on the population dynamics. Despite a vast amount of research exploring these challenges, there have been few studies exploring the underlying demographic variability of harvested marine fishes using conservation biology and population ecology perspectives. Here we take the available data for 77 stocks that are assessed in the north Atlantic and the northeast Pacific Oceans and reconstruct their demographics using life-tables. This life-table reconstruction enables us to explore the variability of the demographics of these populations using metrics commonly used in conservation biology (i.e., population growth rates, doubling time, lifetime reproductive success, and generation time). In general, these populations have a latent capacity for population growth (median lambda = 1.1) when the effect of fishing was excluded, indeed even when the effect of fishing were accounted for the population mean population growth rate 1.02 overall, although a large minority (37) of the stocks did have a mean population growth rate less than 1 when accounting for fishing mortality. Relatively infrequent, large successful reproductive events resulted in years with exceptional population growth rates, these events were critical for the long term sustainability for many of these populations given the population growth rates when accounting for fishing were less than one 57% of the time.  The population growth rate tended to increase as population abundance declined, this negative density dependence was stronger near the maximum and minimum abundances. The trend at low abundance was largely driven by an increase in the frequency of high values of lambda at low abundance. These general patterns are highly variable between populations and regionally, the most notable differences are the majority of the Atlantic cod populations in the NW Atlantic, these populations had few large recruitment events and the evidence for positive density dependence (i.e., Allee effects or depensation) is relatively strong. The recovery potential of the majority of the populations in this analysis was relatively high, with 60 of the populations able to double in size within 20 years in the absence of fishing, populations with a low recovery potential were constrained to stocks with both a low median population growth rate and low variability in the population growth rate. The majority of stocks have a latent population growth capacity in the absence of fishing, however, there are regional and population specific effects and several populations in this analysis have shown little capacity for population growth even in the absence of fishing. Knowledge of the observed underlying demographic parameters for a population can be used to help sustainably manage the population and can be used to inform the development of rebuilding plans and the species status for populations that have collapsed.

french_abstract: |

header: "Draft working paper --- Do not cite or circulate" # or "" to omit
output:
 csasdown::resdoc_word:
   french: false
   copy_sty: true
   line_nums: true
   line_nums_mod: 1
   lot_lof: false
   draft_watermark: false
   include_section_nums: true
   highlight: tango
# ------------
# End of options to set
knit: (function(input, ...) {
       csasdown::render('_bookdown.yml')
      })
link-citations: true
bibliography: Y:/Zotero/MAR_SABHU.bib
# Any extra LaTeX code for the header:
# header-includes:
# - \usepackage{tikz}
---

```{r setup, echo=FALSE, cache=FALSE, message=FALSE, results='hide', warning=FALSE}
library(knitr)
if (is_latex_output()) {
  knitr_figs_dir <- "knitr-figs-pdf/"
  knitr_cache_dir <- "knitr-cache-pdf/"
  fig_out_type <- "png"
} else {
  knitr_figs_dir <- "knitr-figs-docx/"
  knitr_cache_dir <- "knitr-cache-docx/"
  fig_out_type <- "png"
}
fig_asp <- 0.618
fig_width <- 9
fig_out_width <- "6in"
fig_dpi <- 180
fig_align <- "center"
fig_pos <- "htb"
opts_chunk$set(
  collapse = TRUE,
  warning = FALSE,
  message = FALSE,
  comment = "#>",
  fig.path = knitr_figs_dir,
  cache.path = knitr_cache_dir,
  fig.asp = fig_asp,
  fig.width = fig_width,
  out.width = fig_out_width,
  echo = FALSE,
  #  autodep = TRUE,
  #  cache = TRUE,
  cache.comments = FALSE,
  dev = fig_out_type,
  dpi = fig_dpi,
  fig.align = fig_align,
  fig.pos = fig_pos
)
```

```{r load-libraries-n-data, echo = FALSE, cache = FALSE, message = FALSE, results = 'hide', warning = FALSE}
# add other packages here:
library(dplyr)
library(readr)
library(tibble)
library(csasdown)
# OK, so using the ICES assessments here's what we get for North Sea cod.
library(readxl)
library(tidyverse)
library(rio)
library(ggthemes)
library(cowplot)
library(gtable)
library(viridis)
library(arm)
library(mgcv)
library(lme4)
library(scales)
library(ggh4x)
library(gratia)
theme_set(theme_few(base_size = 14))


# The location of your data
loc <- 'D:/GitHub/ICM'
# The parameters for the doubling time simulation
n.dt.sims <- 1000 # Increase to 1000 for final run, which takes like a full day or something 
n.sim.years <- 100
# If we already have the results don't re-run the models or load data we don't need.
# Note that running the models takes like 4 days to finish!!
load.results <- T
# What tunning model are you running or did you run!
what.2.tune <- 'fec_nm'

#source(paste0(loc,"/Scripts/functions/tuning_sim_fast.R"))

# Download the functions we'll need from github
funs <- c("https://raw.githubusercontent.com/dave-keith/ICM/main/Scripts/functions/simple_Lotka_r.r",
          "https://raw.githubusercontent.com/dave-keith/ICM/main/Scripts/functions/backwards_project.r",
          "https://raw.githubusercontent.com/dave-keith/ICM/main/Scripts/functions/forward_project.r",
          "https://raw.githubusercontent.com/dave-keith/ICM/main/Scripts/functions/tuning_sim_fast.r"
)
  # Now run through a quick loop to load each one, just be sure that your working directory is read/write!
for(fun in funs) 
{
  download.file(fun,destfile = basename(fun))
  source(paste0(getwd(),"/",basename(fun)))
  file.remove(paste0(getwd(),"/",basename(fun)))
}

if(load.results==F)
{
  # Choose 5 ICES stocks that we have the necessary data for
  #ASR <- read_xlsx("../Data/ASR_2018.xlsx" sheet = "ICES")
  ASR1 <- read.csv(paste0(loc,"/Data/ICM_data_NE_atlantic_stocks.csv"))
  ASR <- read.csv(paste0(loc,"/Data/ICM_data_NW_atlantic_stocks.csv"))
  
  
  
  ASR <- rbind(ASR1,ASR)
  datatypes <- unique(gsub(x = names(ASR), pattern = "[^a-zA-Z]", replacement=""))
  
  # Replace 0's in Num.tot with NA so the rest of this works as Freya designed it to...
  ASR$Num.tot[ASR$Num.tot == 0] <- NA
  # we want:
  # Year, Num, WA, Catch, AM, NM, StockID, Management, Area, Order, Family, Genus, Species
  ASRdat <- ASR[,c(grep(x=names(ASR), "Num"),
                   grep(x=names(ASR), "WA"),
                   grep(x=names(ASR), "Catch"),
                   grep(x=names(ASR), "AM"),
                   grep(x=names(ASR), "NM"))]
  # Making all the data numeric that should be numeric
  ASRdat <- apply(X = ASRdat, 2, as.numeric)
  # Getting the species info back
  ASRsp <- ASR[, which(!1:length(names(ASR)) %in% grep(x=names(ASR), ".", fixed=T))]
  # And binding it all back together
  ASR.trim <- cbind(ASRsp, ASRdat)
  # need a unique ID for stock
  #table(ASR.trim$Management, ASR.trim$Species)
  ASR.trim$Stock <- paste0(ASR.trim$Management, "_", ASR.trim$Area, "_", ASR.trim$Genus, "_", ASR.trim$Species)
  
  ASR.long <- ASR.trim %>%
    pivot_longer(!c("Management", "Area", "Order", "Family", "Genus", "Species", "Stock", "Year","Meeting_or_reference","Model","Case","Notes")) %>%
    separate(col=name, into=c("type", "age"), sep = "\\.")
  
  # Something is weird with the mentella stock, I'm going to drop it...
  ASR.long <- ASR.long %>% dplyr::filter(Stock != "ICES-AFWG_DEEP1-2_Sebastes_mentella")
}# end if load results
```

